export type Permissions = { canComplete: boolean; canInspect: boolean; canFinancial: boolean }
export type Asset = { id: string; assetNumber: string; name: string; branchId: string; divisionId: string; branchName: string; status: string; meterUnit: string | null; currentMeterReading: number | null; nextServiceDate: string | null }
export type Job = { id: string; version: string; jobNumber: string; assetId: string; assetNumber: string; assetName: string; branchId: string; branchName: string; assetStatus: string; meterUnit: string | null; currentMeterReading: number | null; status: string; priority: string; serviceType: string; faultDescription: string; completionNotes: string | null; assignedTo: string | null; assignedPersonnelId: string | null; supplier: string | null; supplierId: string | null; sourceType: string; sourceInspectionId: string | null; sourceReference: string | null; reportedByName: string | null; isPreventive: boolean; nextServiceDate: string | null; nextServiceMeter: number | null; serviceIntervalMonths: number | null; warrantyCovered: boolean; warrantyClaimNumber: string | null; parentFailureJobId: string | null; useDetailedCosts?: boolean | null; hasEstimate?: boolean; estimatedCost?: number; actualCost?: number | null; partsCost?: number; labourCost?: number; transportCost?: number; externalServiceCost?: number; taxCost?: number; otherCost?: number; fuelCost?: number; labourHours?: number | null; labourRate?: number | null; invoiceNumber?: string | null; partsUsed: string | null; meterReading: number | null; downtimeHours: number; reportedAt: string; startedAt: string | null; completedAt: string | null; expectedReleaseAt: string | null; releasedAt: string | null; releasedByName: string | null }
export type Counts = { active: number; unassigned: number; inProgress: number; waiting: number; awaitingRelease: number; preventive: number; overdueRepairs?: number }
export type Register = { items: Job[]; total: number; page: number; pageSize: number; counts: Counts; permissions: Permissions }
export type ScheduledAsset = Asset & { nextServiceMeter: number | null; activeJobId: string | null; meterInterval?: number | null; serviceIntervalMonths?: number | null; meterTargetSource?: string; ruleWarning?: string | null; isDue?: boolean; isOverdue?: boolean }
export type Schedule = { items: ScheduledAsset[]; total: number; page: number; pageSize: number; dueCount: number; overdueCount?: number; today: string }
export type Options = { branches: { branchId: string; name: string }[]; technicians: { id: string; fullName: string; employeeNumber: string; branchId: string; divisionId: string; availability: string }[]; suppliers: { id: string; name: string; supplierNumber: string }[]; technicianNames: string[] }
export type Detail = { servicePlan?: ScheduledAsset; job: Job; history: Job[]; audits: { id?: string; action: string; userName: string; occurredAt: string; summary: string }[]; meters: { reading: number; unit: string; recordedAt: string; source: string }[]; inspections: { id: string; stage: string; outcome: string; completedAt: string; completedByName: string; notes: string | null }[]; metrics: { completedJobs: number; downtimeHours: number; repeatFailures: number; totalRecordedCost?: number; totalCost?: number; bookValue?: number | null; costToBookValuePercent?: number | null }; safetyChecks: string[]; permissions: Permissions }
export const money = (value: number) => new Intl.NumberFormat('en-FJ', { style: 'currency', currency: 'FJD' }).format(value)
export const label = (value: string) => value.replace(/([a-z])([A-Z])/g, '$1 $2')
export const date = (value: string | null | undefined, time = false) => value ? new Date(value.length === 10 ? `${value}T00:00:00` : value).toLocaleString('en-FJ', time ? { timeZone: 'Pacific/Fiji', dateStyle: 'medium', timeStyle: 'short' } : { ...(value.length > 10 ? { timeZone: 'Pacific/Fiji' } : {}), dateStyle: 'medium' }) : '—'
export const closed = (job: Job) => ['Completed', 'Cancelled'].includes(job.status)

export const repairOverdue = (job: Job) => !job.releasedAt && job.status !== 'Cancelled' && Boolean(job.expectedReleaseAt && new Date(job.expectedReleaseAt).getTime() < Date.now())
