import { useState } from 'react'
import axios from 'axios'
import { Alert, Box, Button, Card, CardContent, Chip, Grid, Stack, Typography } from '@mui/material'
import { api } from '../api/client'

type Approval = { id:string; canDecide?:boolean; requestNumber:string; status:string; type:string; entityType:string; amount:number; reason:string; createdAt:string; currentStage:number; totalStages:number; stageDecisions:{stageNumber:number;stageName:string;assignedRole:string|null;status:string}[] }
export function ApprovalWorkspace({ approvals, reload }: { approvals:Approval[]; reload:()=>Promise<void> }) {
  const [saving,setSaving]=useState(''), [error,setError]=useState('')
  async function decide(item:Approval,approved:boolean){setSaving(item.id);setError('');try{await api.post(`/corporate-operations/approvals/${item.id}/decision`,{approved,note:approved?'Approved after manager review.':'Rejected after manager review.'});await reload()}catch(e){const data=axios.isAxiosError(e)?e.response?.data:undefined;setError(data?.message??'Only an authorised manager can decide this request.')}finally{setSaving('')}}
  return <Stack spacing={2}>{error&&<Alert severity="error">{error}</Alert>}<Grid container spacing={2}>{approvals.map(x=>{const stage=x.stageDecisions?.find(s=>s.stageNumber===x.currentStage);return <Grid key={x.id} size={{xs:12,md:6}}><Card variant="outlined"><CardContent><Stack direction="row" justifyContent="space-between"><Box><Typography variant="overline">{x.requestNumber}</Typography><Typography variant="h6" fontWeight={800}>{x.type} · FJD {x.amount.toFixed(2)}</Typography></Box><Chip label={x.status}/></Stack><Typography color="text.secondary" mt={1}>{x.reason}</Typography><Typography variant="body2" fontWeight={650} mt={1}>Phase {x.currentStage || 1} of {x.totalStages || 1}: {stage?.stageName || 'Manager approval'}</Typography>{stage?.assignedRole&&<Typography variant="caption" color="text.secondary">Assigned to {stage.assignedRole.replace(/([a-z])([A-Z])/g,'$1 $2')}</Typography>}{x.status==='Pending'&&x.canDecide===true&&<Stack direction="row" gap={1} mt={2}><Button color="error" variant="outlined" disabled={saving===x.id} onClick={()=>void decide(x,false)}>Reject phase</Button><Button variant="contained" disabled={saving===x.id} onClick={()=>void decide(x,true)}>Approve phase</Button></Stack>}</CardContent></Card></Grid>})}</Grid>{approvals.length===0&&<Alert severity="success">No approvals are waiting.</Alert>}</Stack>
}
