import { useEffect, useRef, useState } from 'react'
import { Alert, Autocomplete, Button, Checkbox, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, Stack, TextField } from '@mui/material'
import { api } from '../api/client'
import { toast } from './ToastHost'
import type { SearchHit } from './GlobalSearch'
export default function ComposeNotification({open,onClose}:{open:boolean;onClose:()=>void}) {
  const [all,setAll]=useState(false),[confirmed,setConfirmed]=useState(false),[title,setTitle]=useState(''),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[options,setOptions]=useState<SearchHit[]>([]),[customer,setCustomer]=useState<SearchHit|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState('')
  const requestId=useRef(crypto.randomUUID())
  useEffect(()=>{if(open){requestId.current=crypto.randomUUID();setError('');setConfirmed(false)}},[open])
  useEffect(()=>{if(!open||all||query.trim().length<2){setOptions([]);return}const controller=new AbortController();const timer=setTimeout(()=>void api.get<SearchHit[]>('/search',{params:{q:query},signal:controller.signal}).then(r=>setOptions(r.data.filter(x=>x.kind==='Customer account'))).catch(()=>{if(!controller.signal.aborted)setError('Customer search could not be loaded.')}),300);return()=>{clearTimeout(timer);controller.abort()}},[query,open,all])
  async function send(){setSaving(true);setError('');try{const r=await api.post<{message:string}>('/notifications/send',{requestId:requestId.current,customerId:all?null:customer?.id,allCustomers:all,title,message});toast(r.data.message,'success');setTitle('');setMessage('');setCustomer(null);onClose()}catch(reason){const value=reason as {response?:{data?:{message?:string}}};setError(value.response?.data?.message??'Notification could not be sent. Try again.')}finally{setSaving(false)}}
  return <Dialog open={open} onClose={()=>!saving&&onClose()} fullWidth maxWidth="sm"><DialogTitle>Send customer notification</DialogTitle><DialogContent><Stack spacing={2} pt={1}><Alert severity="info">In-app messages only—not email or SMS. Branch staff can reach customers linked to bookings in their assigned scope; administrators can reach all customers.</Alert>{error&&<Alert severity="error">{error}</Alert>}<FormControlLabel control={<Checkbox checked={all} disabled={saving} onChange={e=>{setAll(e.target.checked);setConfirmed(false)}}/>} label="All accessible customers"/>{!all&&<Autocomplete options={options} value={customer} disabled={saving} filterOptions={x=>x} getOptionLabel={x=>`${x.title} · ${x.detail}`} isOptionEqualToValue={(a,b)=>a.id===b.id} onChange={(_,v)=>setCustomer(v)} onInputChange={(_,v)=>setQuery(v)} renderInput={params=><TextField {...params} label="Find customer by name or number"/>}/>}<TextField label="Title" value={title} disabled={saving} inputProps={{maxLength:160}} onChange={e=>setTitle(e.target.value)}/><TextField label="Message" value={message} disabled={saving} multiline minRows={4} inputProps={{maxLength:2000}} onChange={e=>setMessage(e.target.value)}/>{all&&<FormControlLabel control={<Checkbox checked={confirmed} disabled={saving} onChange={e=>setConfirmed(e.target.checked)}/>} label="I confirm this message should be sent to every accessible customer."/>}</Stack></DialogContent><DialogActions><Button disabled={saving} onClick={onClose}>Cancel</Button><Button variant="contained" disabled={saving||!title.trim()||!message.trim()||(all?!confirmed:!customer)} onClick={()=>void send()}>{saving?'Sending…':'Send notification'}</Button></DialogActions></Dialog>
}
