import axios from 'axios'
import { useEffect, useRef, useState } from 'react'
import { Alert, Autocomplete, Button, Checkbox, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, Stack, TextField } from '@mui/material'
import { api } from '../api/client'
import { toast } from './ToastHost'
import type { SearchHit } from './GlobalSearch'
type StaffRecipient = { id: string; fullName: string }
export default function ComposeNotification({open,onClose}:{open:boolean;onClose:()=>void}) {
  const [all,setAll]=useState(false),[confirmed,setConfirmed]=useState(false),[title,setTitle]=useState(''),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[options,setOptions]=useState<SearchHit[]>([]),[customers,setCustomers]=useState<SearchHit[]>([]),[saving,setSaving]=useState(false),[error,setError]=useState('')
  const [sendEmail,setSendEmail]=useState(true),[emailEnabled,setEmailEnabled]=useState<boolean|null>(null)
  const [staffOptions,setStaffOptions]=useState<StaffRecipient[]>([]),[staff,setStaff]=useState<StaffRecipient[]>([])
  useEffect(()=>{if(!open)return;const controller=new AbortController();void api.get<{staff:StaffRecipient[];emailEnabled:boolean}>('/notifications/targets',{signal:controller.signal}).then(r=>{setStaffOptions(r.data.staff);setEmailEnabled(r.data.emailEnabled)}).catch(()=>{if(!controller.signal.aborted)setError('Could not load staff recipients. Reopen this window to try again.')});return()=>controller.abort()},[open])
  const requestId=useRef(crypto.randomUUID())
  useEffect(()=>{if(open){requestId.current=crypto.randomUUID();setError('');setConfirmed(false)}},[open])
  useEffect(()=>{if(!open||all||query.trim().length<2){setOptions([]);return}const controller=new AbortController();const timer=setTimeout(()=>void api.get<SearchHit[]>('/search',{params:{q:query},signal:controller.signal}).then(r=>setOptions(r.data.filter(x=>x.kind==='Customer account'))).catch(()=>{if(!controller.signal.aborted)setError('Customer search could not be loaded.')}),300);return()=>{clearTimeout(timer);controller.abort()}},[query,open,all])
  async function send(){setSaving(true);setError('');try{const r=await api.post<{message:string}>('/notifications/send',{requestId:requestId.current,customerIds:all?[]:customers.map(x=>x.id),allCustomers:all,sendEmail,recipientUserIds:staff.map(x=>x.id),title,message});toast(r.data.message,'success');setTitle('');setMessage('');setCustomers([]);setStaff([]);onClose()}catch(reason){const data=axios.isAxiosError(reason)?reason.response?.data:undefined;setError(data?.message??(data?.errors?Object.values(data.errors).flat().join(' '):'Notification could not be sent. Try again.'))}finally{setSaving(false)}}
  return <Dialog open={open} onClose={()=>!saving&&onClose()} fullWidth maxWidth="sm"><DialogTitle>Send a message</DialogTitle><DialogContent><Stack spacing={2} pt={1}><Alert severity="info">Select customers, staff members or both. Everyone selected receives the same in-app message. Recipients are limited to your permitted scope.</Alert>{error&&<Alert severity="error">{error}</Alert>}<FormControlLabel control={<Checkbox checked={all} disabled={saving} onChange={e=>{setAll(e.target.checked);setConfirmed(false)}}/>} label="All accessible customers"/>{!all&&<Autocomplete multiple disableCloseOnSelect filterSelectedOptions options={options} value={customers} disabled={saving} filterOptions={x=>x} getOptionLabel={x=>`${x.title} · ${x.detail}`} isOptionEqualToValue={(a,b)=>a.id===b.id} onChange={(_,v)=>setCustomers(v)} onInputChange={(_,v)=>setQuery(v)} renderInput={params=><TextField {...params} label="Select customers" helperText={`${customers.length} selected - Search by name or number`}/>}/>}<Autocomplete multiple disableCloseOnSelect filterSelectedOptions options={staffOptions} value={staff} disabled={saving} getOptionLabel={x=>x.fullName} isOptionEqualToValue={(a,b)=>a.id===b.id} onChange={(_,v)=>setStaff(v)} renderInput={params=><TextField {...params} label="Select staff members" helperText={`${staff.length} selected - Optional, can be combined with customers`}/>}/><FormControlLabel control={<Checkbox checked={sendEmail} disabled={saving} onChange={e=>setSendEmail(e.target.checked)}/>} label="Also send by email"/>{sendEmail&&<Alert severity={emailEnabled===false?'warning':'info'}>{emailEnabled===false?'Email delivery is disabled on this server. Messages will still arrive in the notification centre.':'Email copies go to active accounts with verified addresses. Staff email preferences and daily summary settings apply.'}</Alert>}<TextField label="Title" value={title} disabled={saving} inputProps={{maxLength:160}} onChange={e=>setTitle(e.target.value)}/><TextField label="Message" value={message} disabled={saving} multiline minRows={4} inputProps={{maxLength:2000}} onChange={e=>setMessage(e.target.value)}/>{all&&<FormControlLabel control={<Checkbox checked={confirmed} disabled={saving} onChange={e=>setConfirmed(e.target.checked)}/>} label="I confirm this message should be sent to every accessible customer."/>}</Stack></DialogContent><DialogActions><Button disabled={saving} onClick={onClose}>Cancel</Button><Button variant="contained" disabled={saving||!title.trim()||!message.trim()||(all?!confirmed:customers.length+staff.length===0)} onClick={()=>void send()}>{saving?'Sending…':all?`Send to all customers${staff.length?` + ${staff.length} staff`:''}`:`Send to ${customers.length+staff.length} recipient${customers.length+staff.length===1?'':'s'}`}</Button></DialogActions></Dialog>
}
