import { useEffect, useRef, useState } from 'react'
import axios from 'axios'
import { Alert, Autocomplete, Button, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Stack, TextField } from '@mui/material'
import { api } from '../api/client'
import { toast } from './ToastHost'
type Person={id:string;fullName:string;branchId:string|null;divisionId:string|null}
type Targets={staff:Person[];branches:{id:string;name:string}[];divisions:{id:string;name:string}[];roles:string[];isAdministrator:boolean}
export default function ComposeStaffNotification({onClose}:{onClose:()=>void}){
  const [targets,setTargets]=useState<Targets|null>(null),[people,setPeople]=useState<Person[]>([]),[role,setRole]=useState(''),[branch,setBranch]=useState(''),[division,setDivision]=useState('')
  const [title,setTitle]=useState(''),[message,setMessage]=useState(''),[severity,setSeverity]=useState('Info'),[expiry,setExpiry]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false)
  const requestId=useRef(crypto.randomUUID())
  useEffect(()=>{void api.get<Targets>('/notifications/targets').then(r=>setTargets(r.data)).catch(()=>setError('Could not load staff recipients.'))},[])
  async function send(){setSaving(true);setError('');try{const response=await api.post<{message:string}>('/notifications/staff',{requestId:requestId.current,recipientUserIds:people.map(x=>x.id),requiredRole:role||null,branchId:branch||null,divisionId:division||null,title,message,severity,expiresAt:expiry?new Date(expiry).toISOString():null});toast(response.data.message,'success');onClose()}catch(e){const data=axios.isAxiosError(e)?e.response?.data:undefined;setError(data?.message??(data?.errors?Object.values(data.errors).flat().join(' '):'Notification could not be sent.'))}finally{setSaving(false)}}
  const validTarget=Boolean(people.length||role||branch||division)&&Boolean(targets?.isAdministrator||people.length||branch&&division)
  return <Dialog open onClose={()=>!saving&&onClose()} fullWidth maxWidth="sm"><DialogTitle>Notify staff</DialogTitle><DialogContent><Stack spacing={2} pt={1}><Alert severity="info">Select one or more staff members, or choose a scoped audience. Role, branch and division selections are combined. Branch staff cannot message outside their allocated scope.</Alert>{error&&<Alert severity="error">{error}</Alert>}<Autocomplete multiple disableCloseOnSelect filterSelectedOptions disabled={saving} options={targets?.staff??[]} value={people} getOptionLabel={x=>x.fullName} isOptionEqualToValue={(a,b)=>a.id===b.id} onChange={(_,v)=>{setPeople(v);setRole('');setBranch('');setDivision('')}} renderInput={p=><TextField {...p} label="Select staff members (optional)" helperText={`${people.length} selected`}/>}/><TextField select label="Role" disabled={saving||people.length>0} value={role} onChange={e=>setRole(e.target.value)}><MenuItem value="">Any eligible staff role</MenuItem>{targets?.roles.map(x=><MenuItem key={x} value={x}>{x.replace(/([a-z])([A-Z])/g,'$1 $2')}</MenuItem>)}</TextField><Stack direction={{xs:'column',sm:'row'}} spacing={2}><TextField select fullWidth label="Branch" disabled={saving||people.length>0} value={branch} onChange={e=>setBranch(e.target.value)}><MenuItem value="">All branches</MenuItem>{targets?.branches.map(x=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</TextField><TextField select fullWidth label="Division" disabled={saving||people.length>0} value={division} onChange={e=>setDivision(e.target.value)}><MenuItem value="">All divisions</MenuItem>{targets?.divisions.map(x=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</TextField></Stack><TextField label="Title" value={title} inputProps={{maxLength:160}} onChange={e=>setTitle(e.target.value)}/><TextField label="Message" multiline minRows={3} value={message} inputProps={{maxLength:2000}} onChange={e=>setMessage(e.target.value)}/><TextField select label="Priority" value={severity} onChange={e=>setSeverity(e.target.value)}>{['Info','Warning','Urgent'].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField type="datetime-local" label="Expiry (optional)" InputLabelProps={{shrink:true}} value={expiry} onChange={e=>setExpiry(e.target.value)}/></Stack></DialogContent><DialogActions><Button disabled={saving} onClick={onClose}>Cancel</Button><Button variant="contained" disabled={saving||!targets||!validTarget||!title.trim()||!message.trim()} onClick={()=>void send()}>{saving?'Sending…':people.length?`Send to ${people.length} staff member${people.length===1?'':'s'}`:'Send staff notification'}</Button></DialogActions></Dialog>
}
