import { useEffect, useState } from 'react'
import { Alert, Box, Button, Chip, CircularProgress, Dialog, DialogContent, DialogTitle, IconButton, InputAdornment, List, ListItemButton, ListItemText, Stack, TextField, Tooltip, Typography } from '@mui/material'
import SearchOutlined from '@mui/icons-material/SearchOutlined'
import { api } from '../api/client'
import { useAuth } from '../auth/AuthContext'
import { canAccessPage, type AppPage } from '../auth/access'
import { isPageEnabledForDemo } from '../config/demoMode'
const workspaces: {page:AppPage;title:string;url:string}[] = [{page:'dashboard',title:'Dashboard',url:'/staff/dashboard'},{page:'bookings',title:'Bookings and quotations',url:'/staff/bookings'},{page:'rentals',title:'Pickups and returns',url:'/staff/hire-operations'},{page:'assets',title:'Asset register',url:'/staff/assets'},{page:'customers',title:'Customers',url:'/staff/customers'},{page:'users',title:'Staff and access',url:'/staff/staff-access'},{page:'configuration',title:'System configuration and approval rules',url:'/staff/configuration'},{page:'divisions',title:'Organization, branches and divisions',url:'/staff/organization'},{page:'operations',title:'Operations centre',url:'/staff/operations'},{page:'maintenance',title:'Maintenance work',url:'/staff/maintenance'},{page:'scan',title:'Scan asset QR',url:'/staff/scan'}]
export type SearchHit = {id:string;kind:string;title:string;detail:string;url:string}

export function GlobalSearch({ collapsed = false }: { collapsed?: boolean }) {
  const {user}=useAuth()
  const accessible=workspaces.filter(w=>canAccessPage(user?.roles??[],w.page)&&isPageEnabledForDemo(w.page))
  const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[hits,setHits]=useState<SearchHit[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('')
  useEffect(()=>{const key=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();setOpen(value=>!value)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[])
  useEffect(()=>{if(!open)return;const controller=new AbortController();const timer=setTimeout(()=>{setHits([]);setError('');if(query.trim().length<2){setLoading(false);return}setLoading(true);void api.get<SearchHit[]>('/search',{params:{q:query.trim()},signal:controller.signal}).then(r=>setHits(r.data)).catch(()=>{if(!controller.signal.aborted)setError('Search could not be loaded. Please try again.')}).finally(()=>{if(!controller.signal.aborted)setLoading(false)})},300);return()=>{clearTimeout(timer);controller.abort()}},[open,query])
  return <>{collapsed ? <Tooltip title="Search CREMS (⌘K)" placement="right" arrow><IconButton onClick={()=>setOpen(true)} aria-label="Search CREMS" sx={{color:'inherit',border:'1px solid rgba(255,255,255,.18)',borderRadius:2,mx:'auto',display:'flex'}}><SearchOutlined fontSize="small"/></IconButton></Tooltip> : <Button fullWidth variant="outlined" startIcon={<SearchOutlined/>} onClick={()=>setOpen(true)} sx={{justifyContent:'flex-start',color:'inherit',borderColor:'#666',py:1.2,fontSize:12}}>Search CREMS… <Box component="span" sx={{ml:'auto',opacity:.6}}>⌘K</Box></Button>}<Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Search CREMS</DialogTitle><DialogContent><TextField autoFocus fullWidth placeholder="Customer, booking, quotation, asset or job" value={query} onChange={e=>{setQuery(e.target.value);setLoading(e.target.value.trim().length>=2)}} inputProps={{maxLength:100,'aria-label':'Search CREMS records'}} InputProps={{startAdornment:<InputAdornment position="start"><SearchOutlined/></InputAdornment>}}/><Typography variant="caption" color="text.secondary">Results respect your role, branch and division. Enter at least two characters.</Typography>{loading&&<Stack alignItems="center" p={3}><CircularProgress size={24}/></Stack>}{error&&<Alert severity="error">{error}</Alert>}<List>{accessible.filter(w=>w.title.toLowerCase().includes(query.trim().toLowerCase())).map(w=><ListItemButton key={w.page} component="a" href={w.url}><ListItemText primary={w.title}/><Chip size="small" label="Workspace" variant="outlined"/></ListItemButton>)}{hits.filter(hit=>!hit.url.startsWith('/staff/maintenance')||isPageEnabledForDemo('maintenance')).map(hit=><ListItemButton key={`${hit.kind}:${hit.id}`} component="a" href={hit.url} sx={{borderBottom:1,borderColor:'divider',py:1.5}}><ListItemText primary={hit.title} secondary={hit.detail}/><Chip label={hit.kind} size="small" variant="outlined"/></ListItemButton>)}</List>{!loading&&!error&&query.trim().length>=2&&hits.length===0&&!accessible.some(w=>w.title.toLowerCase().includes(query.trim().toLowerCase()))&&<Typography sx={{p:3}} color="text.secondary">No accessible records found. Try a name or reference number.</Typography>}</DialogContent></Dialog></>
}
