import { useState } from 'react'
import axios from 'axios'
import CloseOutlined from '@mui/icons-material/CloseOutlined'
import { Alert, Box, Button, Checkbox, CircularProgress, Dialog, DialogContent, DialogTitle, FormControl, IconButton, InputLabel, MenuItem, Select, Stack, TextField, Typography } from '@mui/material'
import { api } from '../api/client'

type Scan = { submissionId: string; fullName: string; licenceNumber: string; classes: number[]; nameMatches: boolean }
export type LicenceDetails = { status: 'Required' | 'Verified'; licenceNumber: string | null; classes: number[]; hasImage: boolean }
export function validateLicenceConfirmation(file: File | null, number: string, classes: number[]) { if (!file) return 'Choose a JPEG, PNG or PDF file.'; if (!number.trim()) return 'Enter the licence number.'; if (!classes.length) return 'Select at least one licence class.'; return '' }

export function LicenceWorkflowDialog({ open, onClose, onSaved, customerId, manual = false }: { open: boolean; onClose: () => void; onSaved: (licence: LicenceDetails) => void; customerId?: string; manual?: boolean }) {
  const [file, setFile] = useState<File | null>(null); const [scan, setScan] = useState<Scan | null>(null); const [number, setNumber] = useState(''); const [classes, setClasses] = useState<number[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const root = customerId ? `/customers/${customerId}/licence` : '/customer-account/licence'
  const message = (reason: unknown) => axios.isAxiosError(reason)
    ? reason.response?.data?.message ?? reason.response?.data?.detail ?? (reason.code === 'ECONNABORTED' ? 'The licence scan took too long. Please try again.' : 'The licence could not be saved.')
    : 'The licence could not be saved.'
  async function upload(selectedFile = file) { const validation = manual ? validateLicenceConfirmation(selectedFile, number, classes) : !selectedFile ? 'Choose a JPEG, PNG or PDF file.' : ''; if (validation) return setError(validation); setBusy(true); setError(''); try { const body = new FormData(); body.append('file', selectedFile!); if (manual) { body.append('licenceNumber', number); body.append('classes', classes.join(',')); onSaved((await api.post<LicenceDetails>(`${root}/manual`, body)).data); close() } else { const result = (await api.post<Scan>(`${root}/scan`, body, { timeout: 90_000 })).data; setScan(result); setNumber(result.licenceNumber); setClasses(result.classes) } } catch (reason) { setError(message(reason)) } finally { setBusy(false) } }
  async function confirm() { if (!scan) return; setBusy(true); setError(''); try { onSaved((await api.post<LicenceDetails>(`${root}/${scan.submissionId}/confirm`, { licenceNumber: number, classes })).data); close() } catch (reason) { setError(message(reason)) } finally { setBusy(false) } }
  function close() { setFile(null); setScan(null); setNumber(''); setClasses([]); setError(''); onClose() }
  return <Dialog open={open} onClose={() => !busy && close()} disableScrollLock fullWidth maxWidth={customerId ? 'lg' : 'sm'} PaperProps={{ sx: { maxHeight: 'calc(100dvh - 24px)', borderRadius: 2.5 } }}>
    <DialogTitle sx={{ py: 2.5, px: 3.5, display: 'flex', alignItems: 'center', justifyContent: 'space-between', fontSize: 26, fontWeight: 850 }}>{customerId ? 'Capture driver licence' : manual ? 'Enter licence manually' : 'Verify driver licence'}<IconButton aria-label="Close" disabled={busy} onClick={close}><CloseOutlined /></IconButton></DialogTitle>
    <DialogContent dividers sx={{ px: { xs: 2.5, sm: 3.5 }, py: 3 }}><Stack spacing={2}>{error && <Alert severity="error">{error}</Alert>}
      {busy && !manual && !scan && <Stack alignItems="center" justifyContent="center" spacing={1.5} sx={{ minHeight: 210 }}><CircularProgress size={42} sx={{ color: 'text.primary' }} /><Typography variant="h5" fontWeight={850}>Scanning...</Typography><Typography color="text.secondary">Reading licence details.</Typography></Stack>}
      {!busy && !scan && !manual && <><Typography fontWeight={800}>{customerId ? 'Upload requirements' : 'Before you upload'}</Typography><Box component="ul" sx={{ my: 0, pl: 3.25, color: 'text.secondary', lineHeight: 1.8 }}><li>Use a current PDF, JPEG or PNG file up to 5 MB.</li><li>Show the complete licence with every edge visible.</li><li>Avoid blur, glare, shadows and covered details.</li><li>Make sure the driver’s full name, licence number and licence class are readable.</li></Box><Button component="label" variant="contained" fullWidth sx={{ mt: 1 }}>Choose licence {customerId ? 'file' : 'image'}<input hidden type="file" accept="image/jpeg,image/png,application/pdf" onChange={event => { const chosen = event.target.files?.[0] ?? null; setFile(chosen); if (chosen) void upload(chosen) }} /></Button></>}
      {manual && <><Typography color="text.secondary">Upload the licence image and enter its confirmed details. OCR will not run.</Typography><Button component="label" variant="outlined" fullWidth>Choose licence image<input hidden type="file" accept="image/jpeg,image/png,application/pdf" onChange={event => setFile(event.target.files?.[0] ?? null)} /></Button>{file && <Typography variant="body2">Licence image selected</Typography>}</>}
      {scan && <Alert severity="success">Scan completed. Check the details before confirming.</Alert>}
      {scan && <Box><Typography variant="caption" fontWeight={800}>Full name on licence</Typography><Stack direction={{ xs: 'column', sm: 'row' }} gap={1} alignItems={{ sm: 'center' }}><TextField fullWidth value={scan.fullName} InputProps={{ readOnly: true }} error={!scan.nameMatches} /><Typography sx={{ bgcolor: scan.nameMatches ? '#e4f4e8' : '#fdeaea', color: scan.nameMatches ? '#126d39' : '#a9221a', borderRadius: 99, px: 1.5, py: 1, whiteSpace: 'nowrap', fontWeight: 800 }}>{scan.nameMatches ? '✓ Matches account' : 'Does not match account'}</Typography></Stack><Typography variant="caption" color="text.secondary">Compared with the customer’s name already recorded in CREMS.</Typography></Box>}
      {(manual || scan) && <Stack direction={{ xs: 'column', sm: 'row' }} gap={1.5}><TextField fullWidth required label="Licence number" value={number} onChange={event => setNumber(event.target.value)} /><FormControl fullWidth><InputLabel>Licence class</InputLabel><Select multiple label="Licence class" value={classes} renderValue={values => values.join(', ')} MenuProps={{ PaperProps: { sx: { mt: .5, minWidth: 300, border: 1, borderColor: 'divider', borderRadius: 2, boxShadow: 3, '& .MuiList-root': { display: 'grid', gridTemplateColumns: 'repeat(3, minmax(72px, 1fr))', gap: .25, p: 1.25 } } } }} onChange={event => setClasses((event.target.value as number[]).sort((a, b) => a - b))}>{[1,2,3,4,5,6,7,8,9].map(value => <MenuItem key={value} value={value} sx={{ minHeight: 42, borderRadius: 1, px: .75, py: .25, fontWeight: 750, gap: .25 }}><Checkbox size="small" checked={classes.includes(value)} sx={{ p: .5 }} />{value}</MenuItem>)}</Select><Typography variant="caption" color="text.secondary">Select every class shown on the licence.</Typography></FormControl></Stack>}
      {scan && <Typography color="text.secondary">CREMS will store only the confirmed licence number and selected class numbers.</Typography>}
      {(manual || scan) && <Stack spacing={1}><Button variant="contained" fullWidth disabled={busy || (manual && (!file || !number || !classes.length)) || Boolean(scan && (!number || !classes.length || !scan.nameMatches))} onClick={() => void (scan ? confirm() : upload())}>{scan ? 'Confirm and save licence' : 'Save licence details'}</Button>{scan && <Button variant="outlined" fullWidth onClick={() => { setScan(null); setFile(null) }}>Choose another image</Button>}</Stack>}
    </Stack></DialogContent>
  </Dialog>
}
