import { lazy, Suspense, useCallback, useEffect, useRef, useState } from 'react'
import NotificationsOutlined from '@mui/icons-material/NotificationsOutlined'
import { Alert, Badge, Box, Button, Divider, IconButton, List, ListItemButton, ListItemText, Popover, Stack, Typography } from '@mui/material'
import { api } from '../api/client'
import { toast } from './ToastHost'
const ComposeNotification = lazy(() => import('./ComposeNotification'))
type Notice={id:string;title:string;message:string;url:string|null;createdAt:string;isRead:boolean}
type Inbox={items:Notice[];unreadCount:number}

export function NotificationBell({customer=false,canSend=false}:{customer?:boolean;canSend?:boolean}) {
  const endpoint=customer?'/customer-account/notifications':'/notifications'
  const [anchor,setAnchor]=useState<HTMLElement|null>(null),[data,setData]=useState<Inbox>({items:[],unreadCount:0}),[error,setError]=useState(''),[compose,setCompose]=useState(false)
  const seen=useRef<Set<string>|null>(null)
  const load=useCallback(async(signal?:AbortSignal)=>{try{const r=await api.get<Inbox>(endpoint,{signal});if(signal?.aborted)return;const fresh=r.data.items.filter(n=>!n.isRead&&!seen.current?.has(n.id));if(seen.current&&fresh.length)toast(fresh.length===1?fresh[0].title:`${fresh.length} new notifications`);seen.current=new Set(r.data.items.map(n=>n.id));setData(r.data);setError('')}catch{if(!signal?.aborted)setError('Notifications unavailable. Please refresh.')}},[endpoint])
  useEffect(()=>{const controller=new AbortController();let busy=false;const refresh=()=>{if(document.hidden||busy)return;busy=true;void load(controller.signal).finally(()=>{busy=false})};refresh();const timer=window.setInterval(refresh,45000);window.addEventListener('crems:data-changed',refresh);document.addEventListener('visibilitychange',refresh);return()=>{controller.abort();clearInterval(timer);window.removeEventListener('crems:data-changed',refresh);document.removeEventListener('visibilitychange',refresh)}},[load])
  async function read(ids:string[]){if(!ids.length)return;try{await api.post(`${endpoint}/read`,{ids});await load()}catch{setError('Could not mark notifications as read.')}}
  async function visit(n:Notice){await read([n.id]);if(n.url){setAnchor(null);window.location.assign(n.url)}}
  return <><IconButton color="inherit" aria-label={`Notifications, ${data.unreadCount} unread`} onClick={e=>setAnchor(e.currentTarget)}><Badge color="error" badgeContent={data.unreadCount} max={99}><NotificationsOutlined/></Badge></IconButton><Popover open={Boolean(anchor)} anchorEl={anchor} onClose={()=>setAnchor(null)} anchorOrigin={{vertical:'bottom',horizontal:'right'}} transformOrigin={{vertical:'top',horizontal:'right'}}><Box sx={{width:{xs:320,sm:420},maxHeight:'75vh',overflow:'auto'}}><Stack p={2} direction="row" alignItems="center" justifyContent="space-between"><Typography variant="h6">Notifications</Typography><Button size="small" onClick={()=>void load()}>Refresh</Button></Stack><Stack px={2} pb={1} direction="row" gap={1}><Button size="small" disabled={!data.items.some(n=>!n.isRead)} onClick={()=>void read(data.items.filter(n=>!n.isRead).map(n=>n.id))}>Mark shown as read</Button>{canSend&&<Button size="small" onClick={()=>{setCompose(true);setAnchor(null)}}>Send to customers</Button>}</Stack><Divider/>{error&&<Alert severity="warning">{error}</Alert>}<List disablePadding>{data.items.map(n=><ListItemButton key={n.id} onClick={()=>visit(n)} alignItems="flex-start" sx={{px:2,py:1.5,bgcolor:n.isRead?'transparent':'#fff8d9',borderBottom:1,borderColor:'divider'}}><ListItemText primary={<Typography fontWeight={n.isRead?500:750}>{n.title}</Typography>} secondary={<><Typography component="span" variant="body2" sx={{display:'block',whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{n.message}</Typography><Typography component="span" variant="caption">{new Date(n.createdAt).toLocaleString()}</Typography></>}/></ListItemButton>)}</List>{!data.items.length&&!error&&<Typography p={3} color="text.secondary">You’re up to date. New changes and announcements will appear here.</Typography>}<Typography px={2} py={1} variant="caption" color="text.secondary" display="block">Latest 50 notifications · retained in this view for 90 days</Typography></Box></Popover>{canSend&&<Suspense fallback={null}>{compose&&<ComposeNotification open={compose} onClose={()=>setCompose(false)}/>}</Suspense>}</>
}
