import { useCallback, useEffect, useState } from 'react'
import axios from 'axios'
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, Grid, MenuItem, Stack, Tab, Tabs, TextField, Typography } from '@mui/material'
import { api } from '../api/client'

type Lifecycle = { drivers: any[]; payments: any[]; notifications: any[]; incidents: any[]; invoice: any | null; addendums: any[] }
const message = (error: unknown) => { const data = axios.isAxiosError(error) ? error.response?.data : undefined; const errors = data?.errors as Record<string, string[]> | undefined; return errors ? Object.values(errors).flat().join(' ') : 'Unable to save this rental record.' }

export function RentalLifecycleDialog({ booking, onClose }: { booking: { id: string; bookingNumber: string; customerName: string } | null; onClose: () => void }) {
  const [tab, setTab] = useState(0); const [data, setData] = useState<Lifecycle | null>(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const [driver, setDriver] = useState({ fullName: '', licenceNumber: '', licenceClass: '', licenceExpiry: '', verified: true })
  const [payment, setPayment] = useState({ type: 'RentalCharge', method: 'Card', amount: '', receiptNumber: '', note: '' })
  const [incident, setIncident] = useState({ type: 'Damage', occurredAt: new Date().toISOString().slice(0, 16), description: '', location: '', policeReference: '', insuranceClaimNumber: '', estimatedCost: '' })
  const [notification, setNotification] = useState({ channel: 'Email', recipient: '', subject: '', message: '' })
  const [addendum, setAddendum] = useState({ reason: '', newEndAt: '', newDailyRate: '', note: '', customerSignatureName: '' })
  const load = useCallback(async () => { if (!booking) return; try { setData((await api.get<Lifecycle>(`/rentals/${booking.id}/lifecycle`)).data); setError('') } catch { setError('Unable to load lifecycle records.') } }, [booking])
  useEffect(() => { void load() }, [load])
  async function submit(path: string, payload: object, clear: () => void) { if (!booking) return; setSaving(true); setError(''); try { await api.post(`/rentals/${booking.id}/lifecycle/${path}`, payload); clear(); await load() } catch (e) { setError(message(e)) } finally { setSaving(false) } }
  const money = (value: number) => new Intl.NumberFormat('en-FJ', { style: 'currency', currency: 'FJD' }).format(value)
  return <Dialog open={Boolean(booking)} onClose={() => !saving && onClose()} fullWidth maxWidth="lg"><DialogTitle>Rental management · {booking?.bookingNumber}<Typography variant="body2" color="text.secondary">{booking?.customerName}</Typography></DialogTitle><Tabs value={tab} onChange={(_, value) => setTab(value)} variant="scrollable" sx={{ px: 3, borderBottom: 1, borderColor: 'divider' }}><Tab label="Drivers" /><Tab label="Payments" /><Tab label="Incidents" /><Tab label="Notifications" /><Tab label="Addendums" /><Tab label="Final invoice" /></Tabs><DialogContent sx={{ minHeight: 430 }}>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
    {tab === 0 && <Stack spacing={2}><Typography variant="h6">Authorized drivers</Typography>{data?.drivers.map((item) => <Box key={item.id}><Typography fontWeight={700}>{item.fullName} {item.isPrimary && <Chip size="small" label="Primary" />}</Typography><Typography variant="body2">Licence {item.licenceNumber} · Class {item.licenceClass || '—'} · Expires {item.licenceExpiry} · {item.verified ? 'Verified' : 'Pending verification'}</Typography></Box>)}<Divider /><Grid container spacing={2}><Grid size={{ xs: 12, sm: 4 }}><TextField fullWidth label="Full name" value={driver.fullName} onChange={(e) => setDriver({ ...driver, fullName: e.target.value })} /></Grid><Grid size={{ xs: 12, sm: 3 }}><TextField fullWidth label="Licence number" value={driver.licenceNumber} onChange={(e) => setDriver({ ...driver, licenceNumber: e.target.value })} /></Grid><Grid size={{ xs: 12, sm: 2 }}><TextField fullWidth label="Class" value={driver.licenceClass} onChange={(e) => setDriver({ ...driver, licenceClass: e.target.value })} /></Grid><Grid size={{ xs: 12, sm: 3 }}><TextField fullWidth type="date" label="Expiry" InputLabelProps={{ shrink: true }} value={driver.licenceExpiry} onChange={(e) => setDriver({ ...driver, licenceExpiry: e.target.value })} /></Grid></Grid><Button variant="contained" disabled={saving || !driver.fullName || !driver.licenceNumber || !driver.licenceExpiry} onClick={() => void submit('drivers', driver, () => setDriver({ fullName: '', licenceNumber: '', licenceClass: '', licenceExpiry: '', verified: true }))}>Add authorized driver</Button></Stack>}
    {tab === 1 && <Stack spacing={2}><Typography variant="h6">Payments, deposits and refunds</Typography>{data?.payments.map((item) => <Box key={item.id}><Typography fontWeight={700}>{item.type} · {money(item.amount)}</Typography><Typography variant="body2">{item.method} · Receipt {item.receiptNumber} · {item.status}</Typography></Box>)}<Divider /><Grid container spacing={2}><Grid size={{ xs: 12, sm: 3 }}><TextField select fullWidth label="Type" value={payment.type} onChange={(e) => setPayment({ ...payment, type: e.target.value })}>{['RentalCharge','Deposit','Refund','AdditionalCharge'].map(x => <MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField></Grid><Grid size={{ xs: 12, sm: 3 }}><TextField select fullWidth label="Method" value={payment.method} onChange={(e) => setPayment({ ...payment, method: e.target.value })}>{['Cash','Card','BankTransfer','PurchaseOrder','MobileMoney'].map(x => <MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField></Grid><Grid size={{ xs: 12, sm: 3 }}><TextField fullWidth type="number" label="Amount" value={payment.amount} onChange={(e) => setPayment({ ...payment, amount: e.target.value })} /></Grid><Grid size={{ xs: 12, sm: 3 }}><TextField fullWidth label="Receipt number" value={payment.receiptNumber} onChange={(e) => setPayment({ ...payment, receiptNumber: e.target.value })} /></Grid></Grid><Button variant="contained" disabled={saving || !payment.amount} onClick={() => void submit('payments', { ...payment, amount: Number(payment.amount) }, () => setPayment({ type: 'RentalCharge', method: 'Card', amount: '', receiptNumber: '', note: '' }))}>Record payment</Button></Stack>}
    {tab === 2 && <Stack spacing={2}><Typography variant="h6">Damage, accident and insurance cases</Typography>{data?.incidents.map((item) => <Box key={item.id}><Typography fontWeight={700}>{item.incidentNumber} · {item.type} <Chip size="small" label={item.status} /></Typography><Typography variant="body2">{item.description} · Estimate {money(item.estimatedCost)}</Typography></Box>)}<Divider /><Grid container spacing={2}><Grid size={{ xs: 12, sm: 3 }}><TextField select fullWidth label="Type" value={incident.type} onChange={(e) => setIncident({ ...incident, type: e.target.value })}>{['Accident','Damage','Breakdown','Theft','TrafficOffence','Other'].map(x => <MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField></Grid><Grid size={{ xs: 12, sm: 3 }}><TextField fullWidth type="datetime-local" label="Occurred" InputLabelProps={{ shrink: true }} value={incident.occurredAt} onChange={(e) => setIncident({ ...incident, occurredAt: e.target.value })} /></Grid><Grid size={{ xs: 12, sm: 3 }}><TextField fullWidth label="Location" value={incident.location} onChange={(e) => setIncident({ ...incident, location: e.target.value })} /></Grid><Grid size={{ xs: 12, sm: 3 }}><TextField fullWidth type="number" label="Estimated cost" value={incident.estimatedCost} onChange={(e) => setIncident({ ...incident, estimatedCost: e.target.value })} /></Grid><Grid size={{ xs: 12 }}><TextField fullWidth multiline minRows={2} label="Description" value={incident.description} onChange={(e) => setIncident({ ...incident, description: e.target.value })} /></Grid><Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth label="Police reference" value={incident.policeReference} onChange={(e) => setIncident({ ...incident, policeReference: e.target.value })} /></Grid><Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth label="Insurance claim" value={incident.insuranceClaimNumber} onChange={(e) => setIncident({ ...incident, insuranceClaimNumber: e.target.value })} /></Grid></Grid><Button variant="contained" disabled={saving || !incident.description} onClick={() => void submit('incidents', { ...incident, estimatedCost: Number(incident.estimatedCost || 0), evidenceDataUrls: [] }, () => setIncident({ type: 'Damage', occurredAt: new Date().toISOString().slice(0, 16), description: '', location: '', policeReference: '', insuranceClaimNumber: '', estimatedCost: '' }))}>Open incident</Button></Stack>}
    {tab === 3 && <Stack spacing={2}><Typography variant="h6">Customer delivery history</Typography><Alert severity="info">Messages are queued locally. Configure an email/SMS provider before production delivery.</Alert>{data?.notifications.map((item) => <Box key={item.id}><Typography fontWeight={700}>{item.channel} · {item.subject} <Chip size="small" label={item.status} /></Typography><Typography variant="body2">To {item.recipient}: {item.message}</Typography></Box>)}<Divider /><Grid container spacing={2}><Grid size={{ xs: 12, sm: 2 }}><TextField select fullWidth label="Channel" value={notification.channel} onChange={(e) => setNotification({ ...notification, channel: e.target.value })}><MenuItem value="Email">Email</MenuItem><MenuItem value="Sms">SMS</MenuItem></TextField></Grid><Grid size={{ xs: 12, sm: 4 }}><TextField fullWidth label="Recipient" value={notification.recipient} onChange={(e) => setNotification({ ...notification, recipient: e.target.value })} /></Grid><Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth label="Subject" value={notification.subject} onChange={(e) => setNotification({ ...notification, subject: e.target.value })} /></Grid><Grid size={{ xs: 12 }}><TextField fullWidth multiline minRows={2} label="Message" value={notification.message} onChange={(e) => setNotification({ ...notification, message: e.target.value })} /></Grid></Grid><Button variant="contained" disabled={saving || !notification.recipient || !notification.subject || !notification.message} onClick={() => void submit('notifications', notification, () => setNotification({ channel: 'Email', recipient: '', subject: '', message: '' }))}>Queue notification</Button></Stack>}
    {tab === 4 && <Stack spacing={2}><Typography variant="h6">Signed extensions and addendums</Typography>{data?.addendums.map((item) => <Box key={item.id}><Typography fontWeight={700}>{item.addendumNumber}</Typography><Typography variant="body2">{item.reason} · Signed by {item.customerSignatureName}</Typography></Box>)}<Alert severity="warning">An addendum creates a new signed record. It never edits the original agreement.</Alert><Grid container spacing={2}><Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth label="Reason" value={addendum.reason} onChange={(e) => setAddendum({ ...addendum, reason: e.target.value })} /></Grid><Grid size={{ xs: 12, sm: 3 }}><TextField fullWidth type="datetime-local" label="New return date" InputLabelProps={{ shrink: true }} value={addendum.newEndAt} onChange={(e) => setAddendum({ ...addendum, newEndAt: e.target.value })} /></Grid><Grid size={{ xs: 12, sm: 3 }}><TextField fullWidth type="number" label="New daily rate" value={addendum.newDailyRate} onChange={(e) => setAddendum({ ...addendum, newDailyRate: e.target.value })} /></Grid><Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth label="Customer signature name" value={addendum.customerSignatureName} onChange={(e) => setAddendum({ ...addendum, customerSignatureName: e.target.value })} /></Grid><Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth label="Notes" value={addendum.note} onChange={(e) => setAddendum({ ...addendum, note: e.target.value })} /></Grid></Grid><Button variant="contained" disabled={saving || !addendum.reason || !addendum.customerSignatureName} onClick={() => void submit('addendums', { ...addendum, newDailyRate: addendum.newDailyRate ? Number(addendum.newDailyRate) : null, newEndAt: addendum.newEndAt || null }, () => setAddendum({ reason: '', newEndAt: '', newDailyRate: '', note: '', customerSignatureName: '' }))}>Sign addendum</Button></Stack>}
    {tab === 5 && <Stack spacing={2}><Typography variant="h6">Final invoice</Typography>{data?.invoice ? <Box sx={{ p: 3, bgcolor: '#f6f6f3', borderRadius: 2 }}><Typography variant="h5" fontWeight={800}>{data.invoice.invoiceNumber}</Typography><Typography>Subtotal: {money(data.invoice.subtotal)}</Typography><Typography>Tax: {money(data.invoice.taxAmount)}</Typography><Typography variant="h6" fontWeight={800}>Total: {money(data.invoice.total)}</Typography><Typography>Paid: {money(data.invoice.amountPaid)}</Typography><Typography color={data.invoice.balanceDue > 0 ? 'error' : 'success.main'} fontWeight={800}>Balance: {money(data.invoice.balanceDue)}</Typography><Chip sx={{ mt: 1 }} label={data.invoice.status} /></Box> : <Alert severity="info">The final invoice is generated automatically when the return is completed.</Alert>}</Stack>}
  </DialogContent><DialogActions><Button onClick={onClose}>Close</Button></DialogActions></Dialog>
}
