import { useEffect, useState } from 'react'
import axios from 'axios'
import { Alert, Button, Checkbox, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, MenuItem, Stack, TextField, Typography } from '@mui/material'
import { api } from '../api/client'
type Preference={category:string;inAppEnabled:boolean;toastEnabled:boolean;emailEnabled:boolean;emailFrequency:string}
export default function StaffNotificationSettings({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){
  const [items,setItems]=useState<Preference[]>([]),[error,setError]=useState(''),[saving,setSaving]=useState(false)
  useEffect(()=>{void api.get<Preference[]>('/notifications/preferences').then(r=>setItems(r.data)).catch(()=>setError('Could not load your notification preferences.'))},[])
  const update=(index:number,patch:Partial<Preference>)=>setItems(items.map((x,i)=>i===index?{...x,...patch}:x))
  async function save(){setSaving(true);try{await api.put('/notifications/preferences',items);onSaved();onClose()}catch(e){setError(axios.isAxiosError(e)?e.response?.data?.message??'Preferences could not be saved.':'Preferences could not be saved.')}finally{setSaving(false)}}
  return <Dialog open onClose={()=>!saving&&onClose()} fullWidth maxWidth="sm"><DialogTitle>My notification preferences</DialogTitle><DialogContent><Stack spacing={2} pt={1}><Alert severity="info">Muted categories remain available under Include history. Email requires a verified staff address and a configured email provider. Daily summaries queue from 8 am Fiji time. Immediate emails queue within the next notification cycle.</Alert>{error&&<Alert severity="error">{error}</Alert>}{items.map((item,index)=><Stack key={item.category} spacing={1} sx={{p:2,border:1,borderColor:'divider',borderRadius:2}}><Typography fontWeight={750}>{item.category==='Booking'?'Rentals':item.category}</Typography><Stack direction="row" flexWrap="wrap"><FormControlLabel label="In-app" control={<Checkbox checked={item.inAppEnabled} onChange={e=>update(index,{inAppEnabled:e.target.checked})}/>}/><FormControlLabel label="Toast alerts" control={<Checkbox disabled={!item.inAppEnabled} checked={item.toastEnabled} onChange={e=>update(index,{toastEnabled:e.target.checked})}/>}/><FormControlLabel label="Email" control={<Checkbox checked={item.emailEnabled} onChange={e=>update(index,{emailEnabled:e.target.checked})}/>}/></Stack>{item.emailEnabled&&<TextField select size="small" label="Email frequency" value={item.emailFrequency} onChange={e=>update(index,{emailFrequency:e.target.value})}><MenuItem value="Immediate">Immediate</MenuItem><MenuItem value="Daily">Daily summary</MenuItem></TextField>}</Stack>)}</Stack></DialogContent><DialogActions><Button disabled={saving} onClick={onClose}>Cancel</Button><Button variant="contained" disabled={saving||!items.length} onClick={()=>void save()}>{saving?'Saving…':'Save preferences'}</Button></DialogActions></Dialog>
}
