using CREMS.Api.Data;
using CREMS.Api.Domain.Assets;
using CREMS.Api.Domain.Corporate;
using Microsoft.EntityFrameworkCore;

namespace CREMS.Api.Services;
public sealed class BusinessAutomationWorker(IServiceScopeFactory scopes,ILogger<BusinessAutomationWorker> logger):BackgroundService
{
 protected override async Task ExecuteAsync(CancellationToken stoppingToken){while(!stoppingToken.IsCancellationRequested){try{await Run(stoppingToken);}catch(Exception ex){logger.LogError(ex,"CREMS business automation cycle failed");}await Task.Delay(TimeSpan.FromMinutes(15),stoppingToken);}}
 private async Task Run(CancellationToken token){await using var scope=scopes.CreateAsyncScope();var db=scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();var now=DateTimeOffset.UtcNow;var expired=await db.SalesQuotes.Where(x=>x.ValidUntil<now&&(x.Status==QuoteStatus.Draft||x.Status==QuoteStatus.Sent||x.Status==QuoteStatus.Negotiating)).ToListAsync(token);foreach(var q in expired)q.Status=QuoteStatus.Expired;
 var assets=await db.Assets.Where(x=>x.IsActive).ToListAsync(token);foreach(var asset in assets){var dueDate=asset.NextServiceDate.HasValue&&asset.NextServiceDate<=DateOnly.FromDateTime(now.DateTime);var dueMeter=await db.MaintenanceJobs.Where(x=>x.AssetId==asset.Id&&x.NextServiceMeter!=null).OrderByDescending(x=>x.CompletedAt).Select(x=>x.NextServiceMeter).FirstOrDefaultAsync(token);if((dueDate||dueMeter.HasValue&&asset.CurrentMeterReading>=dueMeter)&&!await db.MaintenanceJobs.AnyAsync(x=>x.AssetId==asset.Id&&x.Status!=MaintenanceStatus.Completed&&x.Status!=MaintenanceStatus.Cancelled,token)){db.MaintenanceJobs.Add(new MaintenanceJob{JobNumber=$"MNT-AUTO-{now:yyyyMMdd}-{Guid.NewGuid():N}"[..29],AssetId=asset.Id,BranchId=asset.BranchId,ServiceType="Preventive maintenance",FaultDescription=dueMeter.HasValue?"Meter-based preventive maintenance threshold reached.":"Date-based preventive maintenance interval reached.",IsPreventive=true,Status=MaintenanceStatus.Open});asset.Status=AssetStatus.Maintenance;}}
 var delayed=await db.ApprovalRequests.Include(x=>x.StageDecisions).Where(x=>x.Status==ApprovalStatus.Pending).ToListAsync(token);foreach(var approval in delayed){var stage=approval.StageDecisions.FirstOrDefault(x=>x.StageNumber==approval.CurrentStage);if(stage is not null&&now-approval.CreatedAt>TimeSpan.FromHours(24)&&!await db.ManagementTasks.AnyAsync(x=>!x.IsCompleted&&x.SourceEntityType==nameof(ApprovalRequest)&&x.SourceEntityId==approval.Id,token))db.ManagementTasks.Add(new ManagementTask{BranchId=approval.BranchId,Category=TaskCategory.PendingApproval,Priority=TaskPriority.High,Title=$"Approval delayed: {approval.RequestNumber}",DueAt=now,SourceEntityType=nameof(ApprovalRequest),SourceEntityId=approval.Id});}await db.SaveChangesAsync(token);}
}
