import { useEffect, useState } from 'react'
import { Accordion, AccordionDetails, AccordionSummary, Alert, Box, Button, Card, CardContent, Chip, Grid, Stack, Tab, Table, TableBody, TableCell, TableHead, TableRow, Tabs, TextField, Typography } from '@mui/material'
import ExpandMoreOutlined from '@mui/icons-material/ExpandMoreOutlined'
import { api } from '../api/client'
import { UsersPage } from './UsersPage'
import { ChargeDefinitionsPage } from './ChargeDefinitionsPage'
import { CustomersPage } from './CustomersPage'
import { formatRole, roles } from '../auth/access'

type Summary = { totalUsers: number; activeUsers: number; disabledUsers: number; lockedUsers: number; passwordChangeRequired: number; administrators: number }
type Permission = { role: string; scope: string; permissions: string[] }
type Setting = { id: string; key: string; value: string; category: string; description: string; isSecret: boolean }
type Template = { id: string; key: string; name: string; channel: string; subject: string; body: string; isActive: boolean }
type Health = { status: string; databaseConnected: boolean; pendingMigrations: string[]; queuedNotifications: number; failedNotifications: number; environment: string; version: string; emailProviderConfigured: boolean; smsProviderConfigured: boolean }
type Audit = { id: string; userName: string; action: string; summary: string; occurredAt: string }

const settingNames: Record<string, string> = {
  'rentals.vatRate': 'VAT rate',
  'rentals.defaultDeposit': 'Default security deposit',
  'rentals.defaultCurrency': 'Currency',
  'bookings.holdMinutes': 'Reservation hold time (minutes)',
  'notifications.emailFrom': 'Sender email address',
}

export function AdministrationPage({ userRoles }: { userRoles: string[] }) {
  const isSuperAdministrator = userRoles.includes(roles.superAdministrator)
  const [tab, setTab] = useState(0); const [summary, setSummary] = useState<Summary | null>(null); const [permissions, setPermissions] = useState<Permission[]>([]); const [settings, setSettings] = useState<Setting[]>([]); const [templates, setTemplates] = useState<Template[]>([]); const [health, setHealth] = useState<Health | null>(null); const [audit, setAudit] = useState<Audit[]>([]); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  async function load() { try { const [s, p, set, t, h, a] = await Promise.all([api.get<Summary>('/users/summary'), api.get<Permission[]>('/administration/permissions'), api.get<Setting[]>('/administration/settings'), api.get<Template[]>('/administration/templates'), api.get<Health>('/administration/health'), api.get<Audit[]>('/administration/audit?take=100')]); setSummary(s.data); setPermissions(p.data); setSettings(set.data); setTemplates(t.data); setHealth(h.data); setAudit(a.data); setError('') } catch { setError('Administration could not be loaded. Please try again.') } }
  useEffect(() => { if (isSuperAdministrator) void load() }, [isSuperAdministrator])
  async function saveSetting(item: Setting) { setSaving(true); try { await api.put(`/administration/settings/${encodeURIComponent(item.key)}`, { value: item.value }); await load() } catch { setError('This setting could not be saved.') } finally { setSaving(false) } }
  async function saveTemplate(item: Template) { setSaving(true); try { await api.put(`/administration/templates/${item.id}`, item); await load() } catch { setError('This message could not be saved.') } finally { setSaving(false) } }
  const statCards = summary ? [
    ['Team members', summary.totalUsers], ['Active accounts', summary.activeUsers], ['Needs attention', summary.disabledUsers + summary.lockedUsers + summary.passwordChangeRequired], ['Administrators', summary.administrators],
  ] as const : []

  if (!isSuperAdministrator) return <Box><Box sx={{ px: { xs: 2, sm: 3, lg: 4 }, pt: 3 }}><Typography variant="h4" fontWeight={800}>People & access</Typography><Typography color="text.secondary">Staff accounts and customer portal accounts are managed separately.</Typography><Tabs value={tab > 1 ? 0 : tab} onChange={(_, value) => setTab(value)} sx={{ mt: 2, borderBottom: 1, borderColor: 'divider' }}><Tab label="Staff accounts" /><Tab label="Customer accounts" /></Tabs></Box>{tab === 1 ? <CustomersPage administrationView /> : <UsersPage userRoles={userRoles} />}</Box>

  return <Box>{error && <Alert severity="error" sx={{ m: 3 }}>{error}</Alert>}<Box sx={{ px: { xs: 2, sm: 3, lg: 4 }, pt: 3 }}><Typography variant="h4" fontWeight={800}>People & access</Typography><Typography color="text.secondary">Staff accounts, customer accounts and group-wide system settings.</Typography><Tabs value={tab} onChange={(_, value) => setTab(value)} variant="scrollable" sx={{ mt: 2, borderBottom: 1, borderColor: 'divider' }}><Tab value={0} label="Overview" /><Tab value={1} label="Staff accounts" /><Tab value={5} label="Customer accounts" /><Tab value={2} label="Rental settings" /><Tab value={3} label="Flexible charges" /><Tab value={4} label="Security & system" /></Tabs></Box>
    {tab === 0 && <Box sx={{ p: { xs: 2, sm: 3, lg: 4 } }}><Grid container spacing={2}>{statCards.map(([label, value]) => <Grid key={label} size={{ xs: 12, sm: 6, md: 3 }}><Card variant="outlined"><CardContent><Typography color="text.secondary">{label}</Typography><Typography variant="h3" fontWeight={800}>{value}</Typography></CardContent></Card></Grid>)}</Grid><Card variant="outlined" sx={{ mt: 3 }}><CardContent><Typography variant="h6" fontWeight={800}>Common administrator jobs</Typography><Typography color="text.secondary" sx={{ mb: 2 }}>Add staff, assign their division and branch, reset passwords, or disable accounts. Use the separate Divisions & services and Branches pages for organisation setup.</Typography><Button variant="contained" onClick={() => setTab(1)}>Manage staff accounts</Button><Button sx={{ ml: 1 }} onClick={() => setTab(2)}>Rental settings</Button></CardContent></Card></Box>}
    {tab === 1 && <UsersPage userRoles={userRoles} />}
    {tab === 2 && <Box sx={{ p: { xs: 2, sm: 3, lg: 4 }, maxWidth: 1200 }}><Stack spacing={2}><Alert severity="info">These are shared operating defaults. Division and branch structure is maintained from its own clearly labelled pages.</Alert><Accordion defaultExpanded><AccordionSummary expandIcon={<ExpandMoreOutlined />}><Box><Typography fontWeight={800}>Rental rules</Typography><Typography variant="body2" color="text.secondary">Deposits, taxes and reservation defaults.</Typography></Box></AccordionSummary><AccordionDetails><Stack spacing={2}>{settings.map((item, index) => <Card key={item.id} variant="outlined"><CardContent><Stack direction={{ xs: 'column', sm: 'row' }} gap={2} alignItems={{ sm: 'center' }}><Box sx={{ flex: 1 }}><Typography fontWeight={700}>{settingNames[item.key] ?? item.description ?? item.key}</Typography><Typography variant="body2" color="text.secondary">{item.description}</Typography></Box><TextField size="small" label="Value" type={item.isSecret ? 'password' : 'text'} value={item.value} onChange={(e) => setSettings((current) => current.map((entry, i) => i === index ? { ...entry, value: e.target.value } : entry))} /><Button disabled={saving} onClick={() => void saveSetting(item)}>Save</Button></Stack></CardContent></Card>)}</Stack></AccordionDetails></Accordion><Accordion><AccordionSummary expandIcon={<ExpandMoreOutlined />}><Box><Typography fontWeight={800}>Customer email templates</Typography><Typography variant="body2" color="text.secondary">Confirmation and reminder wording.</Typography></Box></AccordionSummary><AccordionDetails><Stack spacing={2}>{templates.map((item, index) => <Card key={item.id} variant="outlined"><CardContent><Grid container spacing={2}><Grid size={{ xs: 12, md: 4 }}><TextField fullWidth label="Message name" value={item.name} onChange={(e) => setTemplates((current) => current.map((entry, i) => i === index ? { ...entry, name: e.target.value } : entry))} /></Grid><Grid size={{ xs: 12, md: 2 }}><TextField fullWidth label="Send by" value={item.channel} onChange={(e) => setTemplates((current) => current.map((entry, i) => i === index ? { ...entry, channel: e.target.value } : entry))} /></Grid><Grid size={{ xs: 12, md: 6 }}><TextField fullWidth label="Subject" value={item.subject} onChange={(e) => setTemplates((current) => current.map((entry, i) => i === index ? { ...entry, subject: e.target.value } : entry))} /></Grid><Grid size={{ xs: 12 }}><TextField fullWidth multiline minRows={3} label="Message" value={item.body} onChange={(e) => setTemplates((current) => current.map((entry, i) => i === index ? { ...entry, body: e.target.value } : entry))} /></Grid></Grid><Button sx={{ mt: 2 }} variant="contained" disabled={saving} onClick={() => void saveTemplate(item)}>Save template</Button></CardContent></Card>)}</Stack></AccordionDetails></Accordion></Stack></Box>}
    {tab === 3 && <ChargeDefinitionsPage />}
    {tab === 4 && <Box sx={{ p: { xs: 2, sm: 3, lg: 4 }, maxWidth: 1200 }}><Alert severity={health?.status === 'Healthy' ? 'success' : 'warning'} sx={{ mb: 2 }}>{health?.status === 'Healthy' ? 'CREMS is operating normally.' : 'One or more services need attention.'}</Alert><Stack spacing={2}><Accordion defaultExpanded><AccordionSummary expandIcon={<ExpandMoreOutlined />}><Box><Typography fontWeight={800}>Roles and access</Typography><Typography variant="body2" color="text.secondary">What each type of staff member can see and change.</Typography></Box></AccordionSummary><AccordionDetails><Grid container spacing={2}>{permissions.map((item) => <Grid key={item.role} size={{ xs: 12, md: 4 }}><Card variant="outlined" sx={{ height: '100%' }}><CardContent><Typography variant="h6" fontWeight={800}>{formatRole(item.role)}</Typography><Chip label={item.scope} size="small" sx={{ my: 1 }} /><Stack component="ul" spacing={1} sx={{ pl: 2 }}>{item.permissions.map((permission) => <Typography component="li" key={permission} variant="body2">{permission}</Typography>)}</Stack></CardContent></Card></Grid>)}</Grid></AccordionDetails></Accordion><Accordion><AccordionSummary expandIcon={<ExpandMoreOutlined />}><Box><Typography fontWeight={800}>Technical status</Typography><Typography variant="body2" color="text.secondary">For troubleshooting or support.</Typography></Box></AccordionSummary><AccordionDetails>{health && <Grid container spacing={2}>{Object.entries({ Database: health.databaseConnected ? 'Connected' : 'Unavailable', 'Database updates waiting': health.pendingMigrations.length, 'Messages waiting': health.queuedNotifications, 'Failed messages': health.failedNotifications, Email: health.emailProviderConfigured ? 'Ready' : 'Not configured', SMS: health.smsProviderConfigured ? 'Ready' : 'Not configured', Environment: health.environment, Version: health.version }).map(([label, value]) => <Grid key={label} size={{ xs: 12, sm: 6, md: 3 }}><Card variant="outlined"><CardContent><Typography color="text.secondary">{label}</Typography><Typography fontWeight={800}>{String(value)}</Typography></CardContent></Card></Grid>)}</Grid>}</AccordionDetails></Accordion><Accordion><AccordionSummary expandIcon={<ExpandMoreOutlined />}><Box><Typography fontWeight={800}>Activity history</Typography><Typography variant="body2" color="text.secondary">A record of sensitive administrator changes.</Typography></Box></AccordionSummary><AccordionDetails sx={{ overflowX: 'auto' }}><Table size="small"><TableHead><TableRow><TableCell>When</TableCell><TableCell>Administrator</TableCell><TableCell>Action</TableCell><TableCell>Details</TableCell></TableRow></TableHead><TableBody>{audit.map((item) => <TableRow key={item.id}><TableCell>{new Date(item.occurredAt).toLocaleString('en-FJ')}</TableCell><TableCell>{item.userName}</TableCell><TableCell>{item.action}</TableCell><TableCell>{item.summary}</TableCell></TableRow>)}</TableBody></Table></AccordionDetails></Accordion></Stack></Box>}
    {tab === 5 && <CustomersPage administrationView />}
  </Box>
}
