import { useEffect, useState } from 'react'
import AddOutlined from '@mui/icons-material/AddOutlined'
import DeleteOutline from '@mui/icons-material/DeleteOutline'
import { Alert, Box, Button, Card, CardContent, Checkbox, Chip, FormControl, FormControlLabel, Grid, IconButton, InputLabel, MenuItem, Select, Stack, Switch, TextField, Typography } from '@mui/material'
import { api } from '../api/client'

type ScopeItem={id:string;name:string}
type Stage={sequence:number;name:string;assignedRole:string;assignedUserId:null;escalateAfterHours:number;escalationRole:string|null}
type Rule={id:string;name:string;type:string;entityType:string|null;branchId:string|null;divisionId:string|null;minimumAmount:number|null;triggerForEquipment:boolean;triggerForPersonnel:boolean;triggerForOvertime:boolean;isDefaultForBookings:boolean;priority:number;isActive:boolean;stages:Stage[]}
type Form=Omit<Rule,'id'>
const blank=():Form=>({name:'',type:'Booking',entityType:'Booking',branchId:null,divisionId:null,minimumAmount:null,triggerForEquipment:false,triggerForPersonnel:false,triggerForOvertime:false,isDefaultForBookings:false,priority:0,isActive:true,stages:[{sequence:1,name:'Branch manager approval',assignedRole:'BranchManager',assignedUserId:null,escalateAfterHours:24,escalationRole:'Administrator'}]})

export function BookingApprovalRulesPage(){
 const [rules,setRules]=useState<Rule[]>([]),[divisions,setDivisions]=useState<ScopeItem[]>([]),[branches,setBranches]=useState<ScopeItem[]>([]);const [editing,setEditing]=useState<string|null>(null),[form,setForm]=useState<Form>(blank()),[error,setError]=useState(''),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false)
 async function load(){try{const [r,d,b]=await Promise.all([api.get<Rule[]>('/approval-workflows'),api.get<ScopeItem[]>('/divisions'),api.get<ScopeItem[]>('/branches')]);setRules(r.data.filter(x=>x.type==='Booking'));setDivisions(d.data);setBranches(b.data);setError('')}catch{setError('Approval rules could not be loaded.')}} useEffect(()=>{void load()},[])
 function reset(){setEditing(null);setForm(blank());setNotice('')}
 function edit(x:Rule){setEditing(x.id);setForm({...x,stages:[...x.stages].sort((a,b)=>a.sequence-b.sequence)});setNotice('')}
 function updateStage(i:number,p:Partial<Stage>){setForm(f=>({...f,stages:f.stages.map((x,n)=>n===i?{...x,...p}:x)}))}
 function addStage(){setForm(f=>({...f,stages:[...f.stages,{sequence:f.stages.length+1,name:`Approval stage ${f.stages.length+1}`,assignedRole:'BranchManager',assignedUserId:null,escalateAfterHours:24,escalationRole:'Administrator'}]}))}
 function removeStage(i:number){setForm(f=>({...f,stages:f.stages.filter((_,n)=>n!==i).map((x,n)=>({...x,sequence:n+1}))}))}
 function usePreset(kind:'exception'|'highValue'){setEditing(null);setError('');setNotice('');setForm(kind==='exception'?{...blank(),name:'Operational exception approval',triggerForEquipment:true,triggerForPersonnel:true,triggerForOvertime:true,priority:200}:{...blank(),name:'High-value hire approval',minimumAmount:5000,priority:300,stages:[{sequence:1,name:'Branch manager review',assignedRole:'BranchManager',assignedUserId:null,escalateAfterHours:12,escalationRole:'Administrator'},{sequence:2,name:'Administration approval',assignedRole:'Administrator',assignedUserId:null,escalateAfterHours:24,escalationRole:'SuperAdministrator'}]})}
 async function save(){if(!form.name.trim()){setError('Enter a rule name.');return}if(form.stages.length===0){setError('Add at least one approval stage.');return}if(!form.isDefaultForBookings&&form.minimumAmount==null&&!form.triggerForEquipment&&!form.triggerForPersonnel&&!form.triggerForOvertime){setError('Choose at least one trigger, or apply the rule to every booking.');return}setSaving(true);try{const payload={...form,stages:form.stages.map((x,i)=>({...x,sequence:i+1}))};editing?await api.put(`/approval-workflows/${editing}`,payload):await api.post('/approval-workflows',payload);reset();setNotice('Approval rule saved.');await load()}catch{setError('The approval rule could not be saved.')}finally{setSaving(false)}}
 return <Box sx={{p:{xs:2,sm:3,lg:4},maxWidth:1300}}><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" gap={2} mb={3}><Box><Typography variant="h5" fontWeight={850}>Booking approval rules</Typography><Typography color="text.secondary">Routine hires stay quick. Only bookings matching these rules move through manager approval stages.</Typography></Box><Button variant="outlined" startIcon={<AddOutlined/>} onClick={reset}>New rule</Button></Stack>{error&&<Alert severity="error" sx={{mb:2}} onClose={()=>setError('')}>{error}</Alert>}{notice&&<Alert severity="success" sx={{mb:2}}>{notice}</Alert>}<Alert severity="info" sx={{mb:3}}><Typography fontWeight={750}>How rules work</Typography>CREMS uses the most specific matching rule. If rules overlap, the higher rule order wins. Conditions within a rule use OR, and its stages are approved in order. No match means the rental officer can confirm directly.</Alert>
 <Grid container spacing={3}><Grid size={{xs:12,lg:4}}><Stack spacing={1.5}><Typography fontWeight={800}>Recommended starting rules</Typography><Stack direction="row" gap={1} flexWrap="wrap"><Button size="small" variant="outlined" onClick={()=>usePreset('exception')}>Equipment and personnel</Button><Button size="small" variant="outlined" onClick={()=>usePreset('highValue')}>High-value, two stage</Button></Stack>{rules.length===0&&<Alert severity="info">No special rules are active. Rental officers can confirm routine bookings.</Alert>}{rules.map(x=><Card key={x.id} variant="outlined" onClick={()=>edit(x)} sx={{cursor:'pointer',borderColor:editing===x.id?'secondary.main':'divider'}}><CardContent><Stack direction="row" justifyContent="space-between"><Typography fontWeight={800}>{x.name}</Typography><Chip size="small" label={x.isActive?'Active':'Inactive'} color={x.isActive?'success':'default'}/></Stack><Typography variant="body2" color="text.secondary">{x.divisionId?divisions.find(d=>d.id===x.divisionId)?.name:'All divisions'} · {x.branchId?branches.find(b=>b.id===x.branchId)?.name:'All branches'}</Typography><Stack direction="row" gap={.6} flexWrap="wrap" mt={1.5}>{x.minimumAmount!=null&&<Chip size="small" label={`FJD ${x.minimumAmount.toLocaleString()}+`}/>} {x.triggerForEquipment&&<Chip size="small" label="Equipment"/>}{x.triggerForPersonnel&&<Chip size="small" label="Personnel"/>}{x.triggerForOvertime&&<Chip size="small" label="Overtime"/>}{x.isDefaultForBookings&&<Chip size="small" label="Every booking"/>}</Stack><Typography variant="caption" color="text.secondary" display="block" mt={1}>{x.stages.length} sequential stage{x.stages.length===1?'':'s'} · rule order {x.priority}</Typography></CardContent></Card>)}</Stack></Grid>
 <Grid size={{xs:12,lg:8}}><Card variant="outlined"><CardContent><Typography variant="h6" fontWeight={850} mb={2}>{editing?'Edit rule':'Create rule'}</Typography><Grid container spacing={2}><Grid size={12}><TextField fullWidth label="Rule name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Heavy equipment and overtime"/></Grid><Grid size={{xs:12,sm:6}}><FormControl fullWidth><InputLabel>Division scope</InputLabel><Select label="Division scope" value={form.divisionId??''} onChange={e=>setForm({...form,divisionId:e.target.value||null})}><MenuItem value="">All divisions</MenuItem>{divisions.map(x=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</Select></FormControl></Grid><Grid size={{xs:12,sm:6}}><FormControl fullWidth><InputLabel>Branch scope</InputLabel><Select label="Branch scope" value={form.branchId??''} onChange={e=>setForm({...form,branchId:e.target.value||null})}><MenuItem value="">All branches</MenuItem>{branches.map(x=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</Select></FormControl></Grid><Grid size={{xs:12,sm:8}}><TextField fullWidth type="number" label="Minimum booking value (FJD)" value={form.minimumAmount??''} onChange={e=>setForm({...form,minimumAmount:e.target.value===''?null:Number(e.target.value)})}/></Grid><Grid size={{xs:12,sm:4}}><TextField fullWidth type="number" label="Rule order" helperText="Higher wins when rules overlap" value={form.priority} onChange={e=>setForm({...form,priority:Number(e.target.value)})}/></Grid></Grid>
 <Typography fontWeight={800} mt={2}>Trigger when any selected condition applies</Typography><Stack direction={{xs:'column',sm:'row'}} flexWrap="wrap"><FormControlLabel control={<Checkbox checked={form.triggerForEquipment} onChange={e=>setForm({...form,triggerForEquipment:e.target.checked})}/>} label="Equipment hire"/><FormControlLabel control={<Checkbox checked={form.triggerForPersonnel} onChange={e=>setForm({...form,triggerForPersonnel:e.target.checked})}/>} label="Operator / personnel"/><FormControlLabel control={<Checkbox checked={form.triggerForOvertime} onChange={e=>setForm({...form,triggerForOvertime:e.target.checked})}/>} label="Staff overtime"/><FormControlLabel control={<Checkbox checked={form.isDefaultForBookings} onChange={e=>setForm({...form,isDefaultForBookings:e.target.checked})}/>} label="Every booking"/></Stack><Alert severity="info" sx={{mb:2}}>If no active rule matches, a rental officer can confirm the booking directly.</Alert>
 <Stack direction="row" justifyContent="space-between" alignItems="center"><Box><Typography fontWeight={800}>Sequential stages</Typography><Typography variant="body2" color="text.secondary">The next stage opens only after the current one is approved.</Typography></Box><Button size="small" onClick={addStage} disabled={form.stages.length>=5}>Add stage</Button></Stack><Stack spacing={1.5} my={2}>{form.stages.map((x,i)=><Card key={i} variant="outlined"><CardContent><Grid container spacing={1.5} alignItems="center"><Grid size={{xs:10,sm:1}}><Chip label={i+1} color="secondary"/></Grid><Grid size={{xs:2,sm:'auto'}} sx={{order:{sm:5}}}><IconButton aria-label={`Remove stage ${i+1}`} disabled={form.stages.length===1} onClick={()=>removeStage(i)}><DeleteOutline/></IconButton></Grid><Grid size={{xs:12,sm:4}}><TextField fullWidth size="small" label="Stage name" value={x.name} onChange={e=>updateStage(i,{name:e.target.value})}/></Grid><Grid size={{xs:12,sm:3}}><FormControl fullWidth size="small"><InputLabel>Approver role</InputLabel><Select label="Approver role" value={x.assignedRole} onChange={e=>updateStage(i,{assignedRole:e.target.value})}><MenuItem value="BranchManager">Branch manager</MenuItem><MenuItem value="Administrator">Administrator</MenuItem><MenuItem value="SuperAdministrator">Super administrator</MenuItem></Select></FormControl></Grid><Grid size={{xs:12,sm:3}}><TextField fullWidth size="small" type="number" label="Due within hours" value={x.escalateAfterHours} onChange={e=>updateStage(i,{escalateAfterHours:Number(e.target.value)})}/></Grid></Grid></CardContent></Card>)}</Stack><Stack direction="row" justifyContent="space-between" alignItems="center"><FormControlLabel control={<Switch checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/>} label="Rule active"/><Stack direction="row" gap={1}><Button onClick={reset}>Cancel</Button><Button variant="contained" disabled={saving} onClick={()=>void save()}>{saving?'Saving…':'Save rule'}</Button></Stack></Stack></CardContent></Card></Grid></Grid></Box>
}
