import { useEffect, useState } from 'react'
import AddOutlined from '@mui/icons-material/AddOutlined'
import DeleteOutline from '@mui/icons-material/DeleteOutline'
import { Alert, Box, Button, Card, CardContent, Checkbox, Chip, FormControl, FormControlLabel, Grid, IconButton, InputLabel, MenuItem, Select, Stack, Switch, TextField, Tooltip, Typography } from '@mui/material'
import { api } from '../api/client'

type ScopeItem={id:string;name:string}
type Stage={sequence:number;name:string;assignedRole:string;assignedUserId:null;escalateAfterHours:number;escalationRole:string|null}
type Rule={id:string;name:string;type:string;entityType:string|null;branchId:string|null;divisionId:string|null;minimumAmount:number|null;triggerForEquipment:boolean;triggerForPersonnel:boolean;triggerForOvertime:boolean;isDefaultForBookings:boolean;priority:number;isActive:boolean;stages:Stage[]}
type Form=Omit<Rule,'id'>
const standardStages:Stage[]=[{sequence:1,name:'Rental officer review',assignedRole:'RentalOfficer',assignedUserId:null,escalateAfterHours:12,escalationRole:'BranchManager'},{sequence:2,name:'Branch manager approval',assignedRole:'BranchManager',assignedUserId:null,escalateAfterHours:24,escalationRole:'BranchManager'}]
const blank=():Form=>({name:'',type:'Booking',entityType:'Booking',branchId:null,divisionId:null,minimumAmount:null,triggerForEquipment:false,triggerForPersonnel:false,triggerForOvertime:false,isDefaultForBookings:false,priority:0,isActive:true,stages:standardStages.map(x=>({...x}))})
const roleLabel=(role:string|null)=>role==='RentalOfficer'?'Rental officer':role==='BranchManager'?'Branch manager':'Unassigned'
function triggerLabel(rule:Form){const values=[rule.triggerForEquipment&&'equipment',rule.triggerForPersonnel&&'professional personnel',rule.triggerForOvertime&&'staff overtime',rule.minimumAmount!=null&&`value of FJD ${rule.minimumAmount.toLocaleString()} or more`,rule.isDefaultForBookings&&'every booking'].filter(Boolean);return values.length?values.join(' OR '):'No trigger configured'}

export function BookingApprovalRulesPage(){
 const [rules,setRules]=useState<Rule[]>([]),[divisions,setDivisions]=useState<ScopeItem[]>([]),[branches,setBranches]=useState<ScopeItem[]>([]);const [editing,setEditing]=useState<string|null>(null),[form,setForm]=useState<Form>(blank()),[error,setError]=useState(''),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false)
 async function load(){try{const [r,d,b]=await Promise.all([api.get<Rule[]>('/approval-workflows'),api.get<ScopeItem[]>('/divisions'),api.get<ScopeItem[]>('/branches')]);setRules(r.data.filter(x=>x.type==='Booking'&&x.isActive).map(x=>({...x,stages:x.stages.map(stage=>stage.assignedRole==='RentalOfficer'?stage:{...stage,assignedRole:'BranchManager',escalationRole:'BranchManager'})})));setDivisions(d.data);setBranches(b.data);setError('')}catch{setError('Approval rules could not be loaded.')}} useEffect(()=>{void load()},[])
 function reset(){setEditing(null);setForm(blank());setNotice('')}
 function edit(x:Rule){setEditing(x.id);setForm({...x,stages:[...x.stages].sort((a,b)=>a.sequence-b.sequence).map(stage=>stage.assignedRole==='RentalOfficer'?stage:{...stage,assignedRole:'BranchManager',escalationRole:'BranchManager'})});setNotice('')}
 function updateStage(i:number,p:Partial<Stage>){setForm(f=>({...f,stages:f.stages.map((x,n)=>n===i?{...x,...p}:x)}))}
 function addStage(){setForm(f=>({...f,stages:[...f.stages,{sequence:f.stages.length+1,name:'Branch manager approval',assignedRole:'BranchManager',assignedUserId:null,escalateAfterHours:24,escalationRole:'BranchManager'}]}))}
 function removeStage(i:number){setForm(f=>({...f,stages:f.stages.filter((_,n)=>n!==i).map((x,n)=>({...x,sequence:n+1}))}))}
 function usePreset(kind:'equipment'|'overtime'|'highValue'){setEditing(null);setError('');setNotice('');const base=blank();setForm(kind==='equipment'?{...base,name:'Equipment and professional personnel',triggerForEquipment:true,triggerForPersonnel:true,priority:300}:kind==='overtime'?{...base,name:'Staff overtime approval',triggerForOvertime:true,priority:250}:{...base,name:'High-value rental approval',minimumAmount:5000,priority:200})}
 async function save(){if(!form.name.trim()){setError('Enter a rule name.');return}if(form.stages.length===0){setError('Add at least one approval stage.');return}if(!form.isDefaultForBookings&&form.minimumAmount==null&&!form.triggerForEquipment&&!form.triggerForPersonnel&&!form.triggerForOvertime){setError('Choose at least one trigger, or apply the rule to every booking.');return}setSaving(true);try{const payload={...form,stages:form.stages.map((x,i)=>({...x,sequence:i+1}))};editing?await api.put(`/approval-workflows/${editing}`,payload):await api.post('/approval-workflows',payload);reset();setNotice('Approval rule saved.');await load()}catch{setError('The approval rule could not be saved.')}finally{setSaving(false)}}
 return <Box sx={{p:{xs:2,sm:3,lg:4},maxWidth:1500,mx:'auto'}}><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" gap={2} mb={3}><Box><Typography variant="h5" fontWeight={850}>Booking approval rules</Typography><Typography color="text.secondary">Rental officers approve routine bookings. Higher-risk hires continue to the manager responsible for the same branch and division.</Typography></Box><Button variant="outlined" startIcon={<AddOutlined/>} onClick={reset}>Create custom rule</Button></Stack>{error&&<Alert severity="error" sx={{mb:2}} onClose={()=>setError('')}>{error}</Alert>}{notice&&<Alert severity="success" sx={{mb:2}}>{notice}</Alert>}<Alert severity="info" sx={{mb:3}}><Typography fontWeight={750}>Approval path</Typography><strong>Normal rental:</strong> Rental officer approval only. <strong>Matching exception:</strong> Rental officer review → Branch manager approval. Conditions inside one rule use OR. If rules overlap, the more specific scope and then the higher rule order wins.</Alert>
 <Grid container spacing={3} alignItems="flex-start"><Grid size={{xs:12,lg:5}}><Stack spacing={1.5}><Box><Typography fontWeight={800}>Quick rule templates</Typography><Typography variant="body2" color="text.secondary">Choose a template, adjust its scope if needed, then save it.</Typography></Box><Stack direction="row" gap={1} flexWrap="wrap"><Button size="small" variant="outlined" onClick={()=>usePreset('equipment')}>Equipment / personnel</Button><Button size="small" variant="outlined" onClick={()=>usePreset('overtime')}>Staff overtime</Button><Button size="small" variant="outlined" onClick={()=>usePreset('highValue')}>High value</Button></Stack><Typography fontWeight={800} mt={1}>Configured rules</Typography>{rules.length===0&&<Alert severity="info">No exception rules are active. Rental officers can confirm routine bookings.</Alert>}{rules.map(x=><Card key={x.id} variant="outlined" onClick={()=>edit(x)} sx={{cursor:'pointer',borderColor:editing===x.id?'secondary.main':'divider',bgcolor:editing===x.id?'rgba(255,232,0,.06)':'background.paper'}}><CardContent><Stack direction="row" justifyContent="space-between" gap={1}><Box><Typography fontWeight={850}>{x.name}</Typography><Typography variant="caption" color="text.secondary">{x.divisionId?divisions.find(d=>d.id===x.divisionId)?.name:'All divisions'} · {x.branchId?branches.find(b=>b.id===x.branchId)?.name:'All branches'} · Order {x.priority}</Typography></Box><Chip size="small" label={x.isActive?'Active':'Inactive'} color={x.isActive?'success':'default'}/></Stack><Box sx={{mt:1.5,p:1.25,borderRadius:1.5,bgcolor:'grey.100'}}><Typography variant="caption" color="text.secondary">WHEN</Typography><Typography variant="body2" fontWeight={700}>{triggerLabel(x)}</Typography></Box><Stack direction="row" gap={.75} alignItems="center" flexWrap="wrap" mt={1.5}>{x.stages.sort((a,b)=>a.sequence-b.sequence).map((stage,index)=><Box key={stage.sequence} sx={{display:'contents'}}>{index>0&&<Typography color="text.secondary">→</Typography>}<Chip size="small" variant="outlined" label={`${stage.sequence}. ${roleLabel(stage.assignedRole)}`}/></Box>)}</Stack></CardContent></Card>)}</Stack></Grid>
 <Grid size={{xs:12,lg:7}}><Card variant="outlined"><CardContent><Typography variant="h6" fontWeight={850} mb={2}>{editing?'Edit rule':'Create rule'}</Typography><Grid container spacing={2}><Grid size={12}><TextField fullWidth label="Rule name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Heavy equipment and overtime"/></Grid><Grid size={{xs:12,sm:6}}><FormControl fullWidth><InputLabel>Division scope</InputLabel><Select label="Division scope" value={form.divisionId??''} onChange={e=>setForm({...form,divisionId:e.target.value||null})}><MenuItem value="">All divisions</MenuItem>{divisions.map(x=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</Select></FormControl></Grid><Grid size={{xs:12,sm:6}}><FormControl fullWidth><InputLabel>Branch scope</InputLabel><Select label="Branch scope" value={form.branchId??''} onChange={e=>setForm({...form,branchId:e.target.value||null})}><MenuItem value="">All branches</MenuItem>{branches.map(x=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</Select></FormControl></Grid><Grid size={{xs:12,sm:8}}><TextField fullWidth type="number" label="Minimum booking value (FJD)" value={form.minimumAmount??''} onChange={e=>setForm({...form,minimumAmount:e.target.value===''?null:Number(e.target.value)})}/></Grid><Grid size={{xs:12,sm:4}}><TextField fullWidth type="number" label="Rule order" helperText="Higher wins when rules overlap" value={form.priority} onChange={e=>setForm({...form,priority:Number(e.target.value)})}/></Grid></Grid>
 <Typography fontWeight={800} mt={2}>Trigger when any selected condition applies</Typography><Stack direction={{xs:'column',sm:'row'}} flexWrap="wrap"><FormControlLabel control={<Checkbox checked={form.triggerForEquipment} onChange={e=>setForm({...form,triggerForEquipment:e.target.checked})}/>} label="Equipment hire"/><FormControlLabel control={<Checkbox checked={form.triggerForPersonnel} onChange={e=>setForm({...form,triggerForPersonnel:e.target.checked})}/>} label="Operator / personnel"/><FormControlLabel control={<Checkbox checked={form.triggerForOvertime} onChange={e=>setForm({...form,triggerForOvertime:e.target.checked})}/>} label="Staff overtime"/><FormControlLabel control={<Checkbox checked={form.isDefaultForBookings} onChange={e=>setForm({...form,isDefaultForBookings:e.target.checked})}/>} label="Every booking"/></Stack><Alert severity="info" sx={{mb:2}}>If no active rule matches, a rental officer can confirm the booking directly.</Alert>
 <Box mt={2}><Stack direction="row" justifyContent="space-between" alignItems="center"><Typography fontWeight={800}>Approval route</Typography><Button size="small" startIcon={<AddOutlined/>} onClick={addStage} disabled={form.stages.length>=5}>Add stage</Button></Stack><Typography variant="body2" color="text.secondary">The rental officer completes the first review when submitting the request. The manager assigned to the same branch and division makes the final decision.</Typography></Box><Stack spacing={1.5} my={2}>{form.stages.map((x,i)=><Card key={i} variant="outlined" sx={{bgcolor:i===0?'grey.50':'rgba(255,232,0,.06)'}}><CardContent><Grid container spacing={1.5} alignItems="center"><Grid size={{xs:12,sm:1}}><Chip label={i+1} color={i===0?'default':'secondary'}/></Grid><Grid size={{xs:12,sm:4}}><TextField fullWidth size="small" label="Stage name" value={x.name} onChange={e=>updateStage(i,{name:e.target.value})}/></Grid><Grid size={{xs:12,sm:3}}><FormControl fullWidth size="small"><InputLabel>Responsible role</InputLabel><Select label="Responsible role" value={x.assignedRole} onChange={e=>updateStage(i,{assignedRole:e.target.value,escalationRole:'BranchManager'})}><MenuItem value="RentalOfficer">Rental officer</MenuItem><MenuItem value="BranchManager">Branch manager</MenuItem></Select></FormControl></Grid><Grid size={{xs:12,sm:3}}><TextField fullWidth size="small" type="number" label="Due within hours" value={x.escalateAfterHours} onChange={e=>updateStage(i,{escalateAfterHours:Number(e.target.value)})}/></Grid><Grid size={{xs:12,sm:1}}><Tooltip title="Delete stage"><IconButton color="error" aria-label="Delete stage" onClick={()=>removeStage(i)}><DeleteOutline/></IconButton></Tooltip></Grid></Grid></CardContent></Card>)}</Stack>{form.stages.length===0&&<Alert severity="warning" sx={{mb:2}}>Add at least one approval stage.</Alert>}<Stack direction="row" justifyContent="space-between" alignItems="center"><FormControlLabel control={<Switch checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/>} label="Rule active"/><Stack direction="row" gap={1}><Button onClick={reset}>Cancel</Button><Button variant="contained" disabled={saving} onClick={()=>void save()}>{saving?'Saving…':'Save rule'}</Button></Stack></Stack></CardContent></Card></Grid></Grid></Box>
}
