import { useCallback, useEffect, useMemo, useState } from 'react'
import axios from 'axios'
import SearchOutlined from '@mui/icons-material/SearchOutlined'
import ArrowForwardOutlined from '@mui/icons-material/ArrowForwardOutlined'
import MoreHorizOutlined from '@mui/icons-material/MoreHorizOutlined'
import WarningAmberOutlined from '@mui/icons-material/WarningAmberOutlined'
import CloseOutlined from '@mui/icons-material/CloseOutlined'
import {
  Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Divider, Drawer, Grid,
  IconButton, InputAdornment, Menu, MenuItem, Pagination, Stack, Tab, Tabs, Table, TableBody,
  TableCell, TableContainer, TableHead, TableRow, TextField, Typography,
} from '@mui/material'
import { api } from '../api/client'

type QueueKey = 'NewRequests' | 'QuotationRequired' | 'AwaitingApproval' | 'Confirmed' | 'Closed'
type Counts = { newRequests: number; quotationRequired: number; awaitingApproval: number; confirmed: number; closed: number }
type QueueRow = { id:string; bookingNumber:string; createdAt:string; status:string; customerName:string; customerEmail:string|null; customerPhone:string|null; customerIsBlocked:boolean; customerType:string; branchName:string; divisionName:string; serviceName:string; assetNumber:string|null; assetName:string|null; category:string|null; startAt:string|null; endAt:string|null; estimatedValue:number; depositRequired:number; warning:string|null }
type QueueResponse = { items:QueueRow[]; counts:Counts; page:number; pageSize:number; total:number }
type Workspace = {
  id:string; bookingNumber:string; status:string; createdAt:string; notes:string|null
  customer:{ customerId:string; customerNumber:string; name:string; type:string; email:string|null; phone:string|null; address:string|null; identificationNumber:string|null; isBlocked:boolean }
  branch:{ branchId:string; name:string; address:string|null; phone:string|null }
  item:null|{ assetId:string; assetNumber:string; name:string; category:string|null; assetStatus:string; divisionId:string|null; division:string|null; service:string|null; startAt:string; endAt:string; dailyRate:number; currentMeterReading:number|null; meterUnit:string|null }
  pricing:{ duration:number; hire:number; discountAmount:number; additionalCharges:number; additionalChargesDescription:string|null; taxRate:number; tax:number; total:number; depositRequired:number; paid:number; balance:number; internalCost:number; charges:{description:string;category:string;quantity:number;unitRate:number;unitCost:number}[] }
  readiness:{ confirmed:boolean; assetAllocated:boolean; customerEligible:boolean; identificationVerified:boolean; licenceVerified:boolean; paymentSatisfied:boolean; preHireInspectionComplete:boolean; agreementSigned:boolean }
  quotation:null|{ id:string; quoteNumber:string; status:string; validUntil:string; subtotal:number; discount:number; tax:number; total:number; version:number; lastEmailedAt:string|null }
  agreement:null|{ agreementNumber:string; status:string; customerSignedAt:string; approvedByName:string; lastEmailedAt:string|null; addendumCount:number }
  approvalRule:null|{workflowName:string;reason:string;stages:{sequence:number;name:string;assignedRole:string|null;escalateAfterHours:number}[]}
  approvals:{requestNumber:string;status:string;amount:number;reason:string;currentStage:number;totalStages:number;decisionNote:string|null;createdAt:string;decidedAt:string|null}[]
  customerRequests:{id:string;caseNumber:string;type:string;priority:string;status:string;subject:string;description:string;createdAt:string;dueAt:string|null}[]
  documents:{id:string;fileName:string;type:string;createdAt:string}[]
  activity:{id:string;action:string;summary:string;userName:string;occurredAt:string}[]
}

const queues:{key:QueueKey;label:string;count:keyof Counts}[] = [
  { key:'NewRequests', label:'New requests', count:'newRequests' }, { key:'QuotationRequired', label:'Quotation required', count:'quotationRequired' },
  { key:'AwaitingApproval', label:'Awaiting approval', count:'awaitingApproval' }, { key:'Confirmed', label:'Confirmed', count:'confirmed' },
  { key:'Closed', label:'Cancelled / expired', count:'closed' },
]
const money = (value:number) => new Intl.NumberFormat('en-FJ',{style:'currency',currency:'FJD'}).format(value)
const date = (value:string|null) => value ? new Intl.DateTimeFormat('en-FJ',{day:'numeric',month:'short',year:'numeric'}).format(new Date(value)) : 'Not set'
const errorText = (reason:unknown, fallback:string) => { const data=axios.isAxiosError(reason)?reason.response?.data:undefined; const errors=data?.errors as Record<string,string[]>|undefined; return errors?Object.values(errors).flat().join(' '):data?.message??fallback }
function primaryLabel(queue:QueueKey, row:QueueRow){ if(queue==='NewRequests')return 'Review request'; if(queue==='QuotationRequired')return 'Prepare quotation'; if(queue==='AwaitingApproval')return 'Review approval'; if(queue==='Confirmed')return 'Prepare pickup'; return 'View record' }

export function BookingsPage(){
  const [queue,setQueue]=useState<QueueKey>('NewRequests'); const [data,setData]=useState<QueueResponse>({items:[],counts:{newRequests:0,quotationRequired:0,awaitingApproval:0,confirmed:0,closed:0},page:1,pageSize:25,total:0})
  const [search,setSearch]=useState(''); const [page,setPage]=useState(1); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
  const [selected,setSelected]=useState<QueueRow|null>(null); const [workspace,setWorkspace]=useState<Workspace|null>(null); const [workspaceLoading,setWorkspaceLoading]=useState(false)
  const [menu,setMenu]=useState<{anchor:HTMLElement;row:QueueRow}|null>(null)
  const load=useCallback(async()=>{setLoading(true);try{const response=await api.get<QueueResponse>('/bookings/work-queue',{params:{queue,search:search||undefined,page,pageSize:25}});setData(response.data);setError('')}catch(reason){setError(errorText(reason,'Booking requests could not be loaded. Please try again.'))}finally{setLoading(false)}},[queue,search,page])
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),search?300:0);return()=>window.clearTimeout(timer)},[load,search])
  async function open(row:QueueRow){setSelected(row);setWorkspace(null);setWorkspaceLoading(true);setError('');try{setWorkspace((await api.get<Workspace>(`/bookings/${row.id}/workspace`)).data)}catch(reason){setError(errorText(reason,'The booking workspace could not be loaded.'))}finally{setWorkspaceLoading(false)}}
  const pageCount=Math.max(1,Math.ceil(data.total/data.pageSize))
  return <Box sx={{p:{xs:2,sm:3,lg:4},maxWidth:1600,mx:'auto'}}>
    <Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" gap={2} mb={3}><Box><Typography variant="h4" fontWeight={800}>Booking requests</Typography><Typography color="text.secondary" mt={.5}>Move each customer request from enquiry to confirmed hire.</Typography></Box><TextField size="small" placeholder="Search reference, customer or asset" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} sx={{width:{xs:'100%',md:380}}} InputProps={{startAdornment:<InputAdornment position="start"><SearchOutlined/></InputAdornment>}}/></Stack>
    {error&&!selected&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}
    <Grid container spacing={2} mb={2}>{[['Needs review',data.counts.newRequests],['Quotation required',data.counts.quotationRequired],['Awaiting approval',data.counts.awaitingApproval],['Confirmed hires',data.counts.confirmed]].map(([label,value])=><Grid key={String(label)} size={{xs:6,md:3}}><Card variant="outlined"><CardContent sx={{py:2}}><Typography variant="body2" color="text.secondary">{label}</Typography><Typography variant="h5" fontWeight={850}>{value}</Typography></CardContent></Card></Grid>)}</Grid>
    <Card variant="outlined" sx={{overflow:'hidden'}}><Tabs value={queue} onChange={(_,value)=>{setQueue(value);setPage(1)}} variant="scrollable" scrollButtons="auto" sx={{px:1,borderBottom:1,borderColor:'divider'}}>{queues.map(item=><Tab key={item.key} value={item.key} label={<Stack direction="row" alignItems="center" gap={1}><span>{item.label}</span><Chip size="small" label={data.counts[item.count]} sx={{height:22,fontWeight:750}}/></Stack>}/>)}</Tabs>
      {loading?<Box sx={{minHeight:360,display:'grid',placeItems:'center'}}><CircularProgress/></Box>:<>
        <TableContainer sx={{display:{xs:'none',md:'block'}}}><Table><TableHead><TableRow><TableCell>Request</TableCell><TableCell>Customer</TableCell><TableCell>Service and asset</TableCell><TableCell>Hire dates</TableCell><TableCell>Branch</TableCell><TableCell align="right">Estimate</TableCell><TableCell>Stage / warning</TableCell><TableCell align="right">Next action</TableCell></TableRow></TableHead><TableBody>{data.items.map(row=><TableRow key={row.id} hover><TableCell><Typography fontWeight={800}>{row.bookingNumber}</Typography><Typography variant="caption" color="text.secondary">Received {date(row.createdAt)}</Typography></TableCell><TableCell><Typography fontWeight={650}>{row.customerName}</Typography><Typography variant="caption" color="text.secondary">{row.customerType} · {row.customerPhone||row.customerEmail||'No contact'}</Typography></TableCell><TableCell><Typography variant="body2" fontWeight={650}>{row.divisionName} · {row.serviceName}</Typography><Typography variant="caption" color="text.secondary">{row.assetName?`${row.assetName} (${row.assetNumber})`:row.category||'Asset not allocated'}</Typography></TableCell><TableCell><Typography variant="body2">{date(row.startAt)} – {date(row.endAt)}</Typography></TableCell><TableCell>{row.branchName}</TableCell><TableCell align="right"><Typography fontWeight={750}>{money(row.estimatedValue)}</Typography></TableCell><TableCell>{row.warning?<Chip icon={<WarningAmberOutlined/>} size="small" color="warning" variant="outlined" label={row.warning}/>:<Chip size="small" color={queue==='Confirmed'?'success':'default'} variant="outlined" label={queues.find(x=>x.key===queue)?.label}/>}</TableCell><TableCell align="right"><Stack direction="row" justifyContent="flex-end"><Button size="small" variant="contained" endIcon={<ArrowForwardOutlined/>} onClick={()=>void open(row)}>{primaryLabel(queue,row)}</Button><IconButton onClick={e=>setMenu({anchor:e.currentTarget,row})}><MoreHorizOutlined/></IconButton></Stack></TableCell></TableRow>)}{data.items.length===0&&<TableRow><TableCell colSpan={8}><EmptyQueue queue={queue}/></TableCell></TableRow>}</TableBody></Table></TableContainer>
        <Stack spacing={1.5} sx={{display:{xs:'flex',md:'none'},p:2}}>{data.items.map(row=><Card key={row.id} variant="outlined"><CardContent><Stack direction="row" justifyContent="space-between" gap={1}><Box><Typography fontWeight={800}>{row.bookingNumber}</Typography><Typography variant="body2" fontWeight={650}>{row.customerName}</Typography></Box><Typography fontWeight={800}>{money(row.estimatedValue)}</Typography></Stack><Divider sx={{my:1.5}}/><Typography variant="body2">{row.divisionName} · {row.serviceName}</Typography><Typography variant="body2" color="text.secondary">{row.assetName||row.category||'Asset not allocated'} · {date(row.startAt)} – {date(row.endAt)}</Typography>{row.warning&&<Alert severity="warning" sx={{mt:1.5,py:0}}>{row.warning}</Alert>}<Button fullWidth variant="contained" sx={{mt:2}} onClick={()=>void open(row)}>{primaryLabel(queue,row)}</Button></CardContent></Card>)}{data.items.length===0&&<EmptyQueue queue={queue}/>}</Stack>
        {data.total>data.pageSize&&<Stack alignItems="center" sx={{p:2,borderTop:1,borderColor:'divider'}}><Pagination count={pageCount} page={page} onChange={(_,value)=>setPage(value)}/></Stack>}
      </>}
    </Card>
    <Menu open={Boolean(menu)} anchorEl={menu?.anchor} onClose={()=>setMenu(null)}><MenuItem onClick={()=>{if(menu)void open(menu.row);setMenu(null)}}>Open full details</MenuItem><MenuItem disabled>Print request summary</MenuItem></Menu>
    <BookingWorkspace open={Boolean(selected)} row={selected} data={workspace} loading={workspaceLoading} error={error} onClose={()=>{setSelected(null);setWorkspace(null);setError('')}} onChanged={async()=>{if(selected)await open(selected);await load()}} setError={setError}/>
  </Box>
}

function EmptyQueue({queue}:{queue:QueueKey}){return <Box sx={{py:8,textAlign:'center'}}><Typography fontWeight={750}>Nothing waiting here</Typography><Typography variant="body2" color="text.secondary">{queue==='NewRequests'?'New online and counter requests will appear here.':'Records move here automatically as staff complete each stage.'}</Typography></Box>}

function BookingWorkspace({open,row,data,loading,error,onClose,onChanged,setError}:{open:boolean;row:QueueRow|null;data:Workspace|null;loading:boolean;error:string;onClose:()=>void;onChanged:()=>Promise<void>;setError:(v:string)=>void}){
  const [section,setSection]=useState(0); const [saving,setSaving]=useState(false); const [notice,setNotice]=useState(''); const [discount,setDiscount]=useState('0'); const [tax,setTax]=useState('15'); const [rate,setRate]=useState('0'); const [operator,setOperator]=useState('0'); const [transport,setTransport]=useState('0'); const [deposit,setDeposit]=useState('0'); const [revision,setRevision]=useState('Initial quotation')
  useEffect(()=>{if(data){setRate(String(data.item?.dailyRate??0));setDiscount(String(data.pricing.discountAmount));setTax(String(data.pricing.taxRate));setDeposit(String(data.pricing.depositRequired));setSection(0)}},[data])
  const days=data?.pricing.duration??1; const quoteTotal=useMemo(()=>{const subtotal=days*Number(rate||0)+Number(operator||0)+Number(transport||0)-Number(discount||0);return Math.max(0,subtotal)*(1+Number(tax||0)/100)},[days,rate,operator,transport,discount,tax])
  async function confirm(){if(!data)return;setSaving(true);setNotice('');try{const response=await api.patch<{outcome?:string;workflowName?:string}>(`/bookings/${data.id}/status`,{status:'Confirmed',note:'All booking requirements reviewed in booking workspace.'});if(response.data?.outcome==='AwaitingApproval'){setNotice(`Submitted through ${response.data.workflowName??'the configured approval route'}.`);setSection(2)}else setNotice('Booking confirmed.');await onChanged()}catch(reason){setError(errorText(reason,'This request could not be confirmed or submitted for approval.'))}finally{setSaving(false)}}
  async function cancel(){if(!data||!window.confirm('Cancel this booking request? This action is recorded in the audit history.'))return;setSaving(true);try{await api.patch(`/bookings/${data.id}/status`,{status:'Cancelled',note:'Cancelled from booking workspace.'});onClose();await onChanged()}catch(reason){setError(errorText(reason,'This request could not be cancelled.'))}finally{setSaving(false)}}
  async function saveQuote(){if(!data?.item)return;setSaving(true);try{const lines=[{description:`${data.item.name} hire`,quantity:days,rate:Number(rate),costRate:0,unit:'Day',category:'BaseHire'},{description:'Operator / driver',quantity:1,rate:Number(operator),costRate:0,unit:'Unit',category:'Operator'},{description:'Transport / delivery',quantity:1,rate:Number(transport),costRate:0,unit:'Unit',category:'Transport'}].filter(x=>x.rate>0);await api.post(`/bookings/${data.id}/quotation`,{validUntil:new Date(Date.now()+7*86400000).toISOString(),discount:Number(discount||0),taxRate:Number(tax||0),revisionReason:revision,lines});await onChanged();setSection(2)}catch(reason){setError(errorText(reason,'The quotation could not be prepared.'))}finally{setSaving(false)}}
  async function sendQuote(){if(!data?.quotation)return;setSaving(true);try{await api.post(`/corporate-operations/quotes/${data.quotation.id}/send`);await onChanged()}catch(reason){setError(errorText(reason,'The quotation could not be emailed. Check approval and customer email requirements.'))}finally{setSaving(false)}}
  const requirements=data?[['Booking confirmed',data.readiness.confirmed],['Asset allocated',data.readiness.assetAllocated],['Customer eligible',data.readiness.customerEligible],['Deposit satisfied',data.readiness.paymentSatisfied],['Pre-hire inspection',data.readiness.preHireInspectionComplete],['Agreement signed',data.readiness.agreementSigned]] as const:[]
  return <Drawer anchor="right" open={open} onClose={()=>!saving&&onClose()} PaperProps={{sx:{width:{xs:'100%',md:780},maxWidth:'100%'}}}><Stack sx={{height:'100%'}}><Box sx={{p:{xs:2,sm:3},borderBottom:1,borderColor:'divider'}}><Stack direction="row" justifyContent="space-between" alignItems="flex-start"><Box><Typography variant="overline" color="text.secondary">Booking workspace</Typography><Typography variant="h5" fontWeight={850}>{row?.bookingNumber}</Typography><Typography color="text.secondary">{row?.customerName} · {row?.branchName}</Typography></Box><IconButton onClick={onClose}><CloseOutlined/></IconButton></Stack></Box>
    {loading?<Box sx={{flex:1,display:'grid',placeItems:'center'}}><CircularProgress/></Box>:data&&<><Tabs value={section} onChange={(_,v)=>setSection(v)} variant="scrollable" scrollButtons="auto" sx={{px:2,borderBottom:1,borderColor:'divider'}}><Tab label="Request"/><Tab label="Pricing"/><Tab label="Approval"/><Tab label="Documents"/><Tab label="Activity"/></Tabs><Box sx={{p:{xs:2,sm:3},overflowY:'auto',flex:1}}><Stack spacing={3}>{error&&<Alert severity="error">{error}</Alert>}{notice&&<Alert severity="success">{notice}</Alert>}
      {section===0&&<><Grid container spacing={2}><Info label="Customer" value={`${data.customer.name} (${data.customer.customerNumber})`} detail={`${data.customer.type} · ${data.customer.phone||data.customer.email||'No contact recorded'}`}/><Info label="Requested service" value={`${data.item?.division||'Division not set'} · ${data.item?.service||'General hire'}`} detail={data.item?`${data.item.name} (${data.item.assetNumber})`:'Asset not allocated'}/><Info label="Hire period" value={`${date(data.item?.startAt??null)} – ${date(data.item?.endAt??null)}`} detail={`${data.pricing.duration} billable day${data.pricing.duration===1?'':'s'}`}/><Info label="Branch" value={data.branch.name} detail={data.branch.address||data.branch.phone||undefined}/></Grid>{data.customer.isBlocked&&<Alert severity="error">This customer is blocked. Resolve the account restriction before proceeding.</Alert>}{data.customerRequests.filter(x=>x.status!=='Resolved'&&x.status!=='Closed').map(request=><Alert key={request.id} severity={request.subject.startsWith('Extension request')?'warning':'info'}><Typography fontWeight={800}>{request.subject}</Typography><Typography variant="body2" sx={{whiteSpace:'pre-line'}}>{request.description}</Typography><Typography variant="caption">{request.caseNumber} · {request.status} · submitted {new Date(request.createdAt).toLocaleString('en-FJ')}</Typography></Alert>)}<Box><Typography fontWeight={800} mb={1.25}>Progress and missing requirements</Typography><Grid container spacing={1}>{requirements.map(([label,done])=><Grid key={label} size={{xs:6,sm:4}}><Chip size="small" color={done?'success':'default'} variant={done?'filled':'outlined'} label={`${done?'✓':'○'} ${label}`} sx={{width:'100%',justifyContent:'flex-start'}}/></Grid>)}</Grid></Box>{data.notes&&<Box><Typography fontWeight={800}>Internal notes</Typography><Typography variant="body2" color="text.secondary" sx={{whiteSpace:'pre-line'}}>{data.notes}</Typography></Box>}</>}
      {section===1&&<><Alert severity="info">Customers see selling prices only. Internal cost and margin remain staff-only.</Alert><Grid container spacing={2}><Grid size={{xs:12,sm:6}}><TextField fullWidth type="number" label="Hire rate per day (FJD)" value={rate} onChange={e=>setRate(e.target.value)}/></Grid><Grid size={{xs:12,sm:6}}><TextField fullWidth value={`${days} day${days===1?'':'s'}`} label="Automatically calculated duration" disabled/></Grid><Grid size={{xs:12,sm:6}}><TextField fullWidth type="number" label="Operator / driver charge" value={operator} onChange={e=>setOperator(e.target.value)}/></Grid><Grid size={{xs:12,sm:6}}><TextField fullWidth type="number" label="Transport / delivery charge" value={transport} onChange={e=>setTransport(e.target.value)}/></Grid><Grid size={{xs:12,sm:4}}><TextField fullWidth type="number" label="Deposit" value={deposit} onChange={e=>setDeposit(e.target.value)}/></Grid><Grid size={{xs:12,sm:4}}><TextField fullWidth type="number" label="Discount" value={discount} onChange={e=>setDiscount(e.target.value)}/></Grid><Grid size={{xs:12,sm:4}}><TextField fullWidth type="number" label="VAT %" value={tax} onChange={e=>setTax(e.target.value)}/></Grid></Grid><TextField label="Revision reason" value={revision} onChange={e=>setRevision(e.target.value)}/><Card variant="outlined"><CardContent><Stack direction="row" justifyContent="space-between"><Box><Typography color="text.secondary">Customer quotation total</Typography><Typography variant="caption">Hire, services, discount and VAT</Typography></Box><Typography variant="h5" fontWeight={850}>{money(quoteTotal)}</Typography></Stack><Divider sx={{my:2}}/><Stack direction="row" justifyContent="space-between"><Typography variant="body2" color="text.secondary">Internal cost (staff only)</Typography><Typography variant="body2" fontWeight={750}>{money(data.pricing.internalCost)}</Typography></Stack></CardContent></Card><Button variant="contained" onClick={()=>void saveQuote()} disabled={saving||!data.item}>{saving?'Saving quotation…':data.quotation?'Save new revision':'Prepare quotation'}</Button></>}
      {section===2&&<>{data.quotation?<Card variant="outlined"><CardContent><Stack direction="row" justifyContent="space-between"><Box><Typography fontWeight={850}>{data.quotation.quoteNumber}</Typography><Typography variant="body2" color="text.secondary">Version {data.quotation.version} · expires {date(data.quotation.validUntil)}</Typography></Box><Chip label={data.quotation.status} color="info" variant="outlined"/></Stack><Divider sx={{my:2}}/><Stack direction="row" justifyContent="space-between" alignItems="center"><Typography variant="h5" fontWeight={850}>{money(data.quotation.total)}</Typography><Button variant="contained" disabled={saving||data.quotation.status!=='Draft'} onClick={()=>void sendQuote()}>{data.quotation.lastEmailedAt?'Resend quotation':'Email quotation'}</Button></Stack>{data.quotation.lastEmailedAt&&<Typography variant="caption" color="text.secondary">Last emailed {new Date(data.quotation.lastEmailedAt).toLocaleString('en-FJ')}</Typography>}</CardContent></Card>:<Alert severity="warning">Prepare the quotation before requesting approval or confirming this booking.</Alert>}{data.approvals.length===0?<Typography color="text.secondary">No approval is required yet.</Typography>:data.approvals.map(item=><Card key={item.requestNumber} variant="outlined"><CardContent><Stack direction="row" justifyContent="space-between"><Typography fontWeight={800}>{item.requestNumber}</Typography><Chip size="small" label={item.status} color={item.status==='Approved'?'success':item.status==='Rejected'?'error':'warning'}/></Stack><Typography variant="body2" mt={1}>{item.reason}</Typography><Typography variant="caption" color="text.secondary">Stage {item.currentStage} of {item.totalStages}</Typography></CardContent></Card>)}</>}
      {section===3&&<>{data.documents.length===0?<Alert severity="info">No files are attached. Identification, quotation, inspection, agreement and invoice documents will appear here as the hire progresses.</Alert>:data.documents.map(item=><Card key={item.id} variant="outlined"><CardContent><Typography fontWeight={750}>{item.fileName}</Typography><Typography variant="caption" color="text.secondary">{item.type} · {date(item.createdAt)}</Typography></CardContent></Card>)}</>}
      {section===4&&<>{data.activity.length===0?<Typography color="text.secondary">No staff activity has been recorded yet.</Typography>:data.activity.map(item=><Box key={item.id} sx={{pl:2,borderLeft:'3px solid',borderColor:'secondary.main'}}><Typography fontWeight={750}>{item.action}</Typography><Typography variant="body2">{item.summary}</Typography><Typography variant="caption" color="text.secondary">{item.userName} · {new Date(item.occurredAt).toLocaleString('en-FJ')}</Typography></Box>)}</>}
    </Stack></Box><Stack direction="row" gap={1} sx={{p:2,borderTop:1,borderColor:'divider',bgcolor:'background.paper'}}>{data.status==='Draft'&&<Button color="error" onClick={()=>void cancel()} disabled={saving}>Cancel request</Button>}<Box sx={{flex:1}}/>{data.status==='Draft'&&<Button variant="contained" onClick={()=>void confirm()} disabled={saving||data.customer.isBlocked||data.approvals.some(x=>x.status==='Pending')}>{data.approvals.some(x=>x.status==='Pending')?'Awaiting approval':data.approvalRule?'Submit for approval':'Confirm booking'}</Button>}{data.status==='Confirmed'&&<Button variant="contained" disabled>Continue in Hire operations</Button>}</Stack></>}
  </Stack></Drawer>
}
function Info({label,value,detail}:{label:string;value:string;detail?:string}){return <Grid size={{xs:12,sm:6}}><Typography variant="overline" color="text.secondary">{label}</Typography><Typography fontWeight={750}>{value}</Typography>{detail&&<Typography variant="body2" color="text.secondary">{detail}</Typography>}</Grid>}
