import { useState, type FormEvent } from 'react'
import axios from 'axios'
import { Alert, Box, Button, Card, CardContent, Stack, TextField, Typography } from '@mui/material'
import { api } from '../api/client'
import { useAuth } from '../auth/AuthContext'

export function ChangePasswordPage() {
  const { refreshSession, logout } = useAuth(); const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); if (newPassword !== confirm) { setError('The new passwords do not match.'); return } setSaving(true); setError(''); try { await api.post('/auth/change-password', { currentPassword, newPassword }); await refreshSession() } catch (requestError) { const data = axios.isAxiosError(requestError) ? requestError.response?.data : undefined; const errors = data?.errors as Record<string, string[]> | undefined; setError(errors ? Object.values(errors).flat().join(' ') : 'Unable to change the password.') } finally { setSaving(false) } }
  return <Box sx={{ minHeight: '100vh', bgcolor: '#f5f5f2', display: 'grid', placeItems: 'center', p: 2 }}><Card sx={{ width: '100%', maxWidth: 500 }}><CardContent sx={{ p: 4 }}><Box component="img" src="/brand/carpenters-logo.png" alt="Carpenters Fiji" sx={{ width: 56, height: 56, mb: 2 }} /><Typography variant="h4" fontWeight={800}>Create a new password</Typography><Typography color="text.secondary" mt={1} mb={3}>An administrator issued a temporary password. For security, replace it before accessing CREMS.</Typography><Box component="form" onSubmit={submit}><Stack spacing={2}>{error && <Alert severity="error">{error}</Alert>}<TextField required type="password" label="Temporary password" value={currentPassword} onChange={(e) => setCurrentPassword(e.target.value)} /><TextField required type="password" label="New password" helperText="Use at least 10 characters with uppercase, lowercase and a number." value={newPassword} onChange={(e) => setNewPassword(e.target.value)} /><TextField required type="password" label="Confirm new password" value={confirm} onChange={(e) => setConfirm(e.target.value)} /><Button type="submit" variant="contained" size="large" disabled={saving || newPassword.length < 10}>{saving ? 'Changing…' : 'Change password and continue'}</Button><Button onClick={() => void logout()}>Sign out</Button></Stack></Box></CardContent></Card></Box>
}
