import { useEffect, useState } from 'react'
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Grid, Stack, Tab, Table, TableBody, TableCell, TableHead, TableRow, Tabs, Typography } from '@mui/material'
import RefreshOutlined from '@mui/icons-material/RefreshOutlined'
import { api } from '../api/client'

type Overview = Record<string, number>
type Workspace = { quotes: any[]; dispatches: any[]; transfers: any[]; pricing: any[]; approvals: any[]; parts: any[]; purchaseOrders: any[]; cases: any[]; tasks: any[]; telematics: any[]; corporateAccounts: any[] }
const dailySections: { key: keyof Workspace; label: string }[] = [{ key: 'tasks', label: 'To do' }, { key: 'dispatches', label: 'Deliveries & collections' }, { key: 'quotes', label: 'Quotes' }, { key: 'approvals', label: 'Waiting for approval' }, { key: 'cases', label: 'Customer issues' }]
const advancedSections: { key: keyof Workspace; label: string }[] = [{ key: 'transfers', label: 'Branch transfers' }, { key: 'pricing', label: 'Rates' }, { key: 'parts', label: 'Parts stock' }, { key: 'purchaseOrders', label: 'Purchase orders' }, { key: 'telematics', label: 'GPS data' }, { key: 'corporateAccounts', label: 'Business accounts' }]
const title = (value: string) => value.replace(/([A-Z])/g, ' $1').replace(/^./, (x) => x.toUpperCase())
const display = (value: unknown) => value === null || value === undefined || value === '' ? '—' : typeof value === 'boolean' ? (value ? 'Yes' : 'No') : typeof value === 'number' ? value.toLocaleString('en-FJ') : String(value)

export function CorporateOperationsPage({ embedded = false }: { embedded?: boolean }) {
  const [overview, setOverview] = useState<Overview | null>(null); const [workspace, setWorkspace] = useState<Workspace | null>(null); const [tab, setTab] = useState(0); const [advanced, setAdvanced] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  async function load() { setLoading(true); try { const [o, w] = await Promise.all([api.get<Overview>('/corporate-operations/overview'), api.get<Workspace>('/corporate-operations/workspace')]); setOverview(o.data); setWorkspace(w.data); setError('') } catch { setError('Unable to load corporate operations. Restart the updated backend and try again.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const sections = advanced ? advancedSections : dailySections; const section = sections[Math.min(tab, sections.length - 1)]; const rows = workspace?.[section.key] ?? []; const hidden = new Set(['id','createdAt','updatedAt','lineItemsJson','linesJson','proofJson','inspectionJson','faultCodesJson','billingContactJson','authorizedContactsJson','jobSitesJson','contractPricingJson']); const columns = rows.length ? Object.keys(rows[0]).filter((key) => !hidden.has(key) && !key.toLowerCase().endsWith('id')).slice(0, 7) : []
  return <Box sx={{ p: { xs: 2, sm: 3, lg: 4 }, pt: embedded ? 3 : undefined, maxWidth: 1600, mx: 'auto' }}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" mb={3}><Box>{!embedded && <><Typography variant="h4" fontWeight={800}>Management</Typography><Typography color="text.secondary">Daily priorities and supporting business operations.</Typography></>}</Box><Stack direction="row"><Button onClick={() => { setAdvanced((value) => !value); setTab(0) }}>{advanced ? 'Back to daily work' : 'More tools'}</Button><Button startIcon={<RefreshOutlined />} onClick={() => void load()}>Refresh</Button></Stack></Stack>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}{loading ? <Box sx={{ minHeight: 360, display: 'grid', placeItems: 'center' }}><CircularProgress /></Box> : <><Grid container spacing={2} mb={3}>{overview && Object.entries(overview).filter(([key]) => ['activeRentals','overdueRentals','todayDispatches','pendingApprovals','lowStockParts','openCases','outstandingReceivables','utilizationPercent'].includes(key)).map(([key, value]) => <Grid key={key} size={{ xs: 6, sm: 4, md: 3 }}><Card variant="outlined"><CardContent><Typography variant="body2" color="text.secondary">{title(key)}</Typography><Typography variant="h4" fontWeight={800}>{key.toLowerCase().includes('receivables') ? `$${value.toLocaleString('en-FJ')}` : key.toLowerCase().includes('percent') ? `${value}%` : value.toLocaleString('en-FJ')}</Typography></CardContent></Card></Grid>)}</Grid><Card variant="outlined"><Box sx={{ p: 2, borderBottom: 1, borderColor: 'divider' }}><Typography fontWeight={800}>{advanced ? 'Supporting tools' : 'What needs attention'}</Typography><Typography variant="body2" color="text.secondary">{advanced ? 'Rates, stock, transfers and integration information.' : 'Work through these lists from left to right during the day.'}</Typography></Box><Tabs value={tab} onChange={(_, value) => setTab(value)} variant="scrollable" sx={{ borderBottom: 1, borderColor: 'divider' }}>{sections.map((item) => <Tab key={item.key} label={item.label} />)}</Tabs><Box sx={{ overflowX: 'auto' }}>{rows.length ? <Table><TableHead><TableRow>{columns.map((column) => <TableCell key={column}>{title(column)}</TableCell>)}</TableRow></TableHead><TableBody>{rows.map((row: any) => <TableRow key={row.id} hover>{columns.map((column) => <TableCell key={column}>{column === 'status' || column === 'priority' || column === 'type' ? <Chip size="small" label={display(row[column])} variant="outlined" /> : display(row[column])}</TableCell>)}</TableRow>)}</TableBody></Table> : <Box sx={{ py: 8, textAlign: 'center' }}><Typography fontWeight={700}>Nothing needs attention here</Typography><Typography color="text.secondary">New {section.label.toLowerCase()} records will appear automatically.</Typography></Box>}</Box></Card></>}
  </Box>
}
