import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import axios from 'axios'
import AddOutlined from '@mui/icons-material/AddOutlined'
import BuildOutlined from '@mui/icons-material/BuildOutlined'
import EditOutlined from '@mui/icons-material/EditOutlined'
import SearchOutlined from '@mui/icons-material/SearchOutlined'
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, Grid, IconButton, InputAdornment, MenuItem, Stack, Tab, Tabs, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Tooltip, Typography } from '@mui/material'
import { api } from '../api/client'
import { PageHeader } from '../components/PageHeader'

type Asset = { id: string; assetNumber: string; name: string; branchName: string; status: string }
type Job = { id: string; jobNumber: string; assetId: string; assetNumber: string; assetName: string; branchName: string; status: string; serviceType: string; faultDescription: string; assignedTo: string | null; supplier: string | null; estimatedCost: number; actualCost: number | null; partsCost:number;labourCost:number;transportCost:number;externalServiceCost:number;taxCost:number;otherCost:number;partsUsed: string | null;invoiceNumber:string|null;meterReading:number|null;downtimeHours:number; reportedAt: string; completedAt: string | null; nextServiceDate: string | null }
type Form = { assetId: string; status: string; serviceType: string; faultDescription: string; assignedTo: string; supplier: string; estimatedCost: string; actualCost: string; partsUsed: string; nextServiceDate: string;partsCost:string;labourCost:string;transportCost:string;externalServiceCost:string;taxCost:string;otherCost:string;invoiceNumber:string;meterReading:string;downtimeHours:string }
const empty: Form = { assetId: '', status: 'Open', serviceType: 'Corrective repair', faultDescription: '', assignedTo: '', supplier: '', estimatedCost: '', actualCost: '', partsUsed: '', nextServiceDate: '',partsCost:'',labourCost:'',transportCost:'',externalServiceCost:'',taxCost:'',otherCost:'',invoiceNumber:'',meterReading:'',downtimeHours:'' }
const statuses = ['Open', 'InProgress', 'WaitingForParts', 'Completed', 'Cancelled']
export function MaintenancePage() {
  const [jobs, setJobs] = useState<Job[]>([]); const [assets, setAssets] = useState<Asset[]>([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(() => new URLSearchParams(window.location.search).get('search') ?? ''); const [queue, setQueue] = useState<'Active'|'Scheduled'|'Costs'|'Completed'>('Active'); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Job | null>(null); const [form, setForm] = useState<Form>(empty)
  const load = useCallback(async () => { setLoading(true); try { const [jobResult, assetResult] = await Promise.all([api.get<Job[]>('/maintenance-jobs'), api.get<Asset[]>('/assets')]); setJobs(jobResult.data); setAssets(assetResult.data) } catch { setError('Unable to load maintenance records.') } finally { setLoading(false) } }, [])
  useEffect(() => {
    // Initial API synchronization for the maintenance register.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load()
  }, [load])
  const visible = useMemo(() => { const term = search.toLowerCase(); return jobs.filter((job) => { const matchesSearch=[job.jobNumber, job.assetNumber, job.assetName, job.branchName, job.serviceType, job.assignedTo].some((value) => value?.toLowerCase().includes(term)); const matchesQueue=queue==='Active'?!['Completed','Cancelled'].includes(job.status):queue==='Scheduled'?Boolean(job.nextServiceDate)&&job.status!=='Cancelled':queue==='Costs'?(job.actualCost??job.estimatedCost)>0:job.status==='Completed'; return matchesSearch&&(term.length>0||matchesQueue) }) }, [jobs, search, queue])
  function openCreate() { setEditing(null); setForm({ ...empty, assetId: assets[0]?.id ?? '' }); setError(''); setOpen(true) }
  function openEdit(job: Job) { setEditing(job); setForm({ assetId: job.assetId, status: job.status, serviceType: job.serviceType, faultDescription: job.faultDescription, assignedTo: job.assignedTo ?? '', supplier: job.supplier ?? '', estimatedCost: String(job.estimatedCost), actualCost: job.actualCost == null ? '' : String(job.actualCost), partsUsed: job.partsUsed ?? '', nextServiceDate: job.nextServiceDate ?? '',partsCost:String(job.partsCost||''),labourCost:String(job.labourCost||''),transportCost:String(job.transportCost||''),externalServiceCost:String(job.externalServiceCost||''),taxCost:String(job.taxCost||''),otherCost:String(job.otherCost||''),invoiceNumber:job.invoiceNumber??'',meterReading:job.meterReading==null?'':String(job.meterReading),downtimeHours:String(job.downtimeHours||'') }); setError(''); setOpen(true) }
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { const payload = { ...form, estimatedCost: Number(form.estimatedCost || 0), actualCost: form.actualCost ? Number(form.actualCost) : null, nextServiceDate: form.nextServiceDate || null,partsCost:Number(form.partsCost||0),labourCost:Number(form.labourCost||0),transportCost:Number(form.transportCost||0),externalServiceCost:Number(form.externalServiceCost||0),taxCost:Number(form.taxCost||0),otherCost:Number(form.otherCost||0),meterReading:form.meterReading?Number(form.meterReading):null,downtimeHours:Number(form.downtimeHours||0) }; if (editing) await api.put(`/maintenance-jobs/${editing.id}`, payload); else await api.post('/maintenance-jobs', payload); setOpen(false); await load() } catch (requestError: unknown) { const data = axios.isAxiosError(requestError) ? requestError.response?.data : undefined; const errors = data?.errors as Record<string, string[]> | undefined; setError(errors ? Object.values(errors).flat().join(' ') : 'Unable to save the maintenance job.') } finally { setSaving(false) } }
  return <Box sx={{ p: { xs: 2, sm: 3, lg: 4 }, maxWidth: 1500, mx: 'auto' }}><PageHeader icon={<BuildOutlined />} title="Maintenance jobs" subtitle="Track faults, technicians, suppliers, parts, costs and service completion." actions={<Stack direction="row" gap={1}><Chip icon={<BuildOutlined />} label={`${jobs.filter((job) => !['Completed', 'Cancelled'].includes(job.status)).length} open`} color="warning" variant="outlined" /><Button variant="contained" startIcon={<AddOutlined />} onClick={openCreate}>Log job</Button></Stack>} />
    {error && !open && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<Card variant="outlined"><CardContent sx={{ p: 0 }}><Tabs value={queue} onChange={(_,value)=>setQueue(value)} variant="scrollable" scrollButtons="auto" sx={{px:1,borderBottom:1,borderColor:'divider'}}><Tab value="Active" label={`Active work (${jobs.filter(job=>!['Completed','Cancelled'].includes(job.status)).length})`}/><Tab value="Scheduled" label={`Preventive schedule (${jobs.filter(job=>job.nextServiceDate&&job.status!=='Cancelled').length})`}/><Tab value="Costs" label="Costs & suppliers"/><Tab value="Completed" label={`Return to service (${jobs.filter(job=>job.status==='Completed').length})`}/></Tabs><Box sx={{ p: 2, borderBottom: 1, borderColor: 'divider' }}><TextField size="small" placeholder="Search job, asset, branch or technician" value={search} onChange={(e) => setSearch(e.target.value)} sx={{ width: { xs: '100%', sm: 430 } }} InputProps={{ startAdornment: <InputAdornment position="start"><SearchOutlined /></InputAdornment> }} /></Box>
      {loading ? <Box sx={{ minHeight: 280, display: 'grid', placeItems: 'center' }}><CircularProgress /></Box> : <TableContainer><Table><TableHead><TableRow sx={{ bgcolor: '#f6f6f3' }}><TableCell>Job</TableCell><TableCell>Asset</TableCell><TableCell>Work</TableCell><TableCell>Assigned</TableCell><TableCell>Cost</TableCell><TableCell>Status</TableCell><TableCell align="right">Edit</TableCell></TableRow></TableHead><TableBody>{visible.map((job) => <TableRow key={job.id} hover><TableCell><Typography fontWeight={700}>{job.jobNumber}</Typography><Typography variant="caption" color="text.secondary">{new Date(job.reportedAt).toLocaleDateString('en-FJ')}</Typography></TableCell><TableCell><Typography variant="body2" fontWeight={650}>{job.assetNumber}</Typography><Typography variant="caption">{job.assetName} · {job.branchName}</Typography></TableCell><TableCell><Typography variant="body2">{job.serviceType}</Typography><Typography variant="caption" color="text.secondary">{job.faultDescription}</Typography></TableCell><TableCell>{job.assignedTo || job.supplier || 'Unassigned'}</TableCell><TableCell>${(job.actualCost ?? job.estimatedCost).toFixed(2)}</TableCell><TableCell><Chip size="small" label={job.status.replace(/([a-z])([A-Z])/g, '$1 $2')} color={job.status === 'Completed' ? 'success' : job.status === 'Cancelled' ? 'default' : 'warning'} variant="outlined" /></TableCell><TableCell align="right"><Tooltip title="Edit maintenance job"><IconButton onClick={() => openEdit(job)}><EditOutlined /></IconButton></Tooltip></TableCell></TableRow>)}{visible.length === 0 && <TableRow><TableCell colSpan={7} align="center" sx={{ py: 8, color: 'text.secondary' }}>No maintenance jobs found.</TableCell></TableRow>}</TableBody></Table></TableContainer>}</CardContent></Card>
    <Dialog open={open} onClose={() => !saving && setOpen(false)} fullWidth maxWidth="md"><Box component="form" onSubmit={save}><DialogTitle>{editing ? `Edit ${editing.jobNumber}` : 'Log maintenance job'}</DialogTitle><DialogContent><Stack spacing={2.25} mt={1}>{error && <Alert severity="error">{error}</Alert>}<Grid container spacing={2}><Grid size={{ xs: 12, sm: 7 }}><TextField fullWidth select required disabled={Boolean(editing)} label="Asset" value={form.assetId} onChange={(e) => setForm({ ...form, assetId: e.target.value })}>{assets.map((asset) => <MenuItem key={asset.id} value={asset.id}>{asset.assetNumber} — {asset.name} ({asset.branchName})</MenuItem>)}</TextField></Grid>{editing && <Grid size={{ xs: 12, sm: 5 }}><TextField fullWidth select label="Status" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}>{statuses.map((status) => <MenuItem key={status} value={status}>{status.replace(/([a-z])([A-Z])/g, '$1 $2')}</MenuItem>)}</TextField></Grid>}</Grid>
      <TextField required label="Service / repair type" value={form.serviceType} onChange={(e) => setForm({ ...form, serviceType: e.target.value })} /><TextField required multiline minRows={2} label="Fault description / work required" value={form.faultDescription} onChange={(e) => setForm({ ...form, faultDescription: e.target.value })} /><Grid container spacing={2}><Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth label="Assigned technician" value={form.assignedTo} onChange={(e) => setForm({ ...form, assignedTo: e.target.value })} /></Grid><Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth label="External supplier" value={form.supplier} onChange={(e) => setForm({ ...form, supplier: e.target.value })} /></Grid><Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth type="number" label="Estimated cost (FJD)" value={form.estimatedCost} onChange={(e) => setForm({ ...form, estimatedCost: e.target.value })} /></Grid>{editing && <Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth type="number" label="Legacy total cost (optional)" helperText="Detailed costs below take priority." value={form.actualCost} onChange={(e) => setForm({ ...form, actualCost: e.target.value })} /></Grid>}</Grid>{editing && <><Typography variant="subtitle2">Actual expense breakdown</Typography><Grid container spacing={2}>{([['partsCost','Parts'],['labourCost','Labour'],['transportCost','Transport'],['externalServiceCost','External service'],['taxCost','Tax'],['otherCost','Other']] as const).map(([key,label])=><Grid key={key} size={{xs:12,sm:4}}><TextField fullWidth type="number" label={`${label} (FJD)`} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></Grid>)}</Grid><Grid container spacing={2}><Grid size={{xs:12,sm:6}}><TextField fullWidth label="Supplier invoice / reference" value={form.invoiceNumber} onChange={e=>setForm({...form,invoiceNumber:e.target.value})}/></Grid><Grid size={{xs:6,sm:3}}><TextField fullWidth type="number" label="Meter reading" value={form.meterReading} onChange={e=>setForm({...form,meterReading:e.target.value})}/></Grid><Grid size={{xs:6,sm:3}}><TextField fullWidth type="number" label="Downtime hours" value={form.downtimeHours} onChange={e=>setForm({...form,downtimeHours:e.target.value})}/></Grid></Grid><TextField multiline minRows={2} label="Parts used" value={form.partsUsed} onChange={(e) => setForm({ ...form, partsUsed: e.target.value })} /></>}<TextField type="date" label="Next scheduled service" InputLabelProps={{ shrink: true }} value={form.nextServiceDate} onChange={(e) => setForm({ ...form, nextServiceDate: e.target.value })} />
    </Stack></DialogContent><DialogActions sx={{ p: 3 }}><Button onClick={() => setOpen(false)} disabled={saving}>Cancel</Button><Button type="submit" variant="contained" disabled={saving || !form.assetId}>{saving ? 'Saving…' : 'Save maintenance job'}</Button></DialogActions></Box></Dialog>
  </Box>
}
