import { useCallback, useEffect, useState } from 'react'
import AssessmentOutlined from '@mui/icons-material/AssessmentOutlined'
import DirectionsCarOutlined from '@mui/icons-material/DirectionsCarOutlined'
import EventAvailableOutlined from '@mui/icons-material/EventAvailableOutlined'
import PeopleOutline from '@mui/icons-material/PeopleOutline'
import { Alert, Avatar, Box, Card, CardContent, CircularProgress, Grid, LinearProgress, Stack, Typography } from '@mui/material'
import { api } from '../api/client'

type Asset = { type: string; status: string; dailyRate: number; branchName: string }
type Booking = { status: string; branchName: string; items: { dailyRate: number; startAt: string; endAt: string }[] }
export function ReportsPage() {
  const [assets, setAssets] = useState<Asset[]>([]); const [bookings, setBookings] = useState<Booking[]>([]); const [customerCount, setCustomerCount] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = useCallback(async () => { try { const [assetResult, bookingResult, customerResult] = await Promise.all([api.get<Asset[]>('/assets'), api.get<Booking[]>('/bookings'), api.get<unknown[]>('/customers')]); setAssets(assetResult.data); setBookings(bookingResult.data); setCustomerCount(customerResult.data.length) } catch { setError('Unable to load reporting data.') } finally { setLoading(false) } }, [])
  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load()
  }, [load])
  if (loading) return <Box sx={{ minHeight: 500, display: 'grid', placeItems: 'center' }}><CircularProgress /></Box>
  const activeRentals = bookings.filter((item) => item.status === 'ConvertedToRental').length; const confirmed = bookings.filter((item) => item.status === 'Confirmed').length; const available = assets.filter((item) => item.status === 'Available').length; const utilization = assets.length ? Math.round((activeRentals / assets.length) * 100) : 0
  const projectedRevenue = bookings.filter((item) => ['Confirmed', 'ConvertedToRental', 'Completed'].includes(item.status)).flatMap((item) => item.items).reduce((sum, item) => sum + item.dailyRate * Math.max(1, Math.ceil((new Date(item.endAt).getTime() - new Date(item.startAt).getTime()) / 86400000)), 0)
  const branchCounts = Object.entries(assets.reduce<Record<string, number>>((result, asset) => ({ ...result, [asset.branchName]: (result[asset.branchName] ?? 0) + 1 }), {})).sort((a, b) => b[1] - a[1])
  const cards = [{ label: 'Total assets', value: assets.length, icon: <DirectionsCarOutlined /> }, { label: 'Available now', value: available, icon: <AssessmentOutlined /> }, { label: 'Confirmed bookings', value: confirmed, icon: <EventAvailableOutlined /> }, { label: 'Customers', value: customerCount, icon: <PeopleOutline /> }]
  return <Box sx={{ p: { xs: 2, sm: 3, lg: 4 }, maxWidth: 1500, mx: 'auto' }}><Box mb={3}><Typography variant="h4" fontWeight={750}>Reports</Typography><Typography color="text.secondary" mt={.5}>A current operational summary based on CREMS records.</Typography></Box>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<Grid container spacing={2.5}>{cards.map((card) => <Grid key={card.label} size={{ xs: 12, sm: 6, lg: 3 }}><Card variant="outlined"><CardContent><Stack direction="row" justifyContent="space-between"><Box><Typography color="text.secondary" variant="body2">{card.label}</Typography><Typography variant="h3" fontWeight={750} mt={1}>{card.value}</Typography></Box><Avatar sx={{ bgcolor: 'secondary.main', color: '#111' }}>{card.icon}</Avatar></Stack></CardContent></Card></Grid>)}</Grid>
    <Grid container spacing={2.5} mt={0}><Grid size={{ xs: 12, md: 6 }}><Card variant="outlined" sx={{ height: '100%' }}><CardContent sx={{ p: 3 }}><Typography variant="h6" fontWeight={700}>Fleet utilization</Typography><Typography color="text.secondary" variant="body2">Active rentals compared with the whole fleet</Typography><Typography variant="h2" fontWeight={800} mt={3}>{utilization}%</Typography><LinearProgress variant="determinate" value={utilization} sx={{ mt: 2, height: 12, borderRadius: 6, bgcolor: '#eee', '& .MuiLinearProgress-bar': { bgcolor: 'secondary.main' } }} /><Typography mt={2} color="text.secondary">{activeRentals} active rentals across {assets.length} assets</Typography></CardContent></Card></Grid><Grid size={{ xs: 12, md: 6 }}><Card variant="outlined" sx={{ height: '100%' }}><CardContent sx={{ p: 3 }}><Typography variant="h6" fontWeight={700}>Projected booking value</Typography><Typography color="text.secondary" variant="body2">Confirmed, active and completed booking days</Typography><Typography variant="h2" fontWeight={800} mt={3}>${projectedRevenue.toLocaleString('en-FJ', { minimumFractionDigits: 2 })}</Typography><Typography color="text.secondary">FJD before taxes, fees and adjustments</Typography></CardContent></Card></Grid></Grid>
    <Card variant="outlined" sx={{ mt: 2.5 }}><CardContent sx={{ p: 3 }}><Typography variant="h6" fontWeight={700} mb={2}>Fleet by branch</Typography><Stack spacing={2}>{branchCounts.map(([branch, count]) => <Box key={branch}><Stack direction="row" justifyContent="space-between" mb={.75}><Typography>{branch}</Typography><Typography fontWeight={700}>{count}</Typography></Stack><LinearProgress variant="determinate" value={assets.length ? count / assets.length * 100 : 0} sx={{ height: 8, borderRadius: 4 }} /></Box>)}</Stack></CardContent></Card></Box>
}
