import { useCallback, useEffect, useState } from 'react'
import AssessmentOutlined from '@mui/icons-material/AssessmentOutlined'
import DirectionsCarOutlined from '@mui/icons-material/DirectionsCarOutlined'
import EventAvailableOutlined from '@mui/icons-material/EventAvailableOutlined'
import PeopleOutline from '@mui/icons-material/PeopleOutline'
import { Alert, Avatar, Box, Button, Card, CardContent, Chip, CircularProgress, Divider, Grid, LinearProgress, Stack, Table, TableBody, TableCell, TableHead, TableRow, Typography } from '@mui/material'
import { api } from '../api/client'
import { PageHeader } from '../components/PageHeader'

type Asset = { type: string; status: string; dailyRate: number; branchName: string }
type Booking = { status: string; branchName: string; items: { dailyRate: number; startAt: string; endAt: string }[] }
type AuditEvent = { id: string; occurredAt: string; userName: string; action: string; entityType: string; summary: string; branchName: string | null }
type Profitability = { totals: { revenue: number; expense: number; profit: number; lossMakingAssets: number }; assets: { id:string; assetNumber:string; name:string; revenue:number; totalExpense:number; grossProfit:number; profitMargin:number; costPerOperatingHour:number; meterUnit:string|null; lossMaking:boolean }[] }
export function ReportsPage() {
  const [assets, setAssets] = useState<Asset[]>([]); const [bookings, setBookings] = useState<Booking[]>([]); const [customerCount, setCustomerCount] = useState(0); const [audit, setAudit] = useState<AuditEvent[]>([]); const [profitability,setProfitability]=useState<Profitability|null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = useCallback(async () => { try { const [assetResult, bookingResult, customerResult, auditResult,profitResult] = await Promise.all([api.get<Asset[]>('/assets'), api.get<Booking[]>('/bookings'), api.get<unknown[]>('/customers'), api.get<AuditEvent[]>('/audit?limit=20'),api.get<Profitability>('/business-operations/asset-profitability')]); setAssets(assetResult.data); setBookings(bookingResult.data); setCustomerCount(customerResult.data.length); setAudit(auditResult.data);setProfitability(profitResult.data) } catch { setError('Unable to load reporting data.') } finally { setLoading(false) } }, [])
  async function exportProfitability(){const response=await api.get('/business-operations/reports/asset-profitability.csv',{responseType:'blob'});const url=URL.createObjectURL(response.data);const link=document.createElement('a');link.href=url;link.download='asset-profitability.csv';link.click();URL.revokeObjectURL(url)}
  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load()
  }, [load])
  if (loading) return <Box sx={{ minHeight: 500, display: 'grid', placeItems: 'center' }}><CircularProgress /></Box>
  const activeRentals = bookings.filter((item) => item.status === 'ConvertedToRental').length; const confirmed = bookings.filter((item) => item.status === 'Confirmed').length; const available = assets.filter((item) => item.status === 'Available').length; const utilization = assets.length ? Math.round((activeRentals / assets.length) * 100) : 0
  const projectedRevenue = bookings.filter((item) => ['Confirmed', 'ConvertedToRental', 'Completed'].includes(item.status)).flatMap((item) => item.items).reduce((sum, item) => sum + item.dailyRate * Math.max(1, Math.ceil((new Date(item.endAt).getTime() - new Date(item.startAt).getTime()) / 86400000)), 0)
  const branchCounts = Object.entries(assets.reduce<Record<string, number>>((result, asset) => ({ ...result, [asset.branchName]: (result[asset.branchName] ?? 0) + 1 }), {})).sort((a, b) => b[1] - a[1])
  const cards = [{ label: 'Total assets', value: assets.length, icon: <DirectionsCarOutlined /> }, { label: 'Available now', value: available, icon: <AssessmentOutlined /> }, { label: 'Confirmed bookings', value: confirmed, icon: <EventAvailableOutlined /> }, { label: 'Customers', value: customerCount, icon: <PeopleOutline /> }]
  return <Box sx={{ p: { xs: 2, sm: 3, lg: 4 }, maxWidth: 1500, mx: 'auto' }}><PageHeader icon={<AssessmentOutlined />} title="Reports" subtitle="A current operational summary based on CREMS records." />{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<Grid container spacing={2.5}>{cards.map((card) => <Grid key={card.label} size={{ xs: 12, sm: 6, lg: 3 }}><Card variant="outlined"><CardContent><Stack direction="row" justifyContent="space-between"><Box><Typography color="text.secondary" variant="body2">{card.label}</Typography><Typography variant="h3" fontWeight={750} mt={1}>{card.value}</Typography></Box><Avatar sx={{ bgcolor: 'secondary.main', color: '#111' }}>{card.icon}</Avatar></Stack></CardContent></Card></Grid>)}</Grid>
    <Grid container spacing={2.5} mt={0}><Grid size={{ xs: 12, md: 6 }}><Card variant="outlined" sx={{ height: '100%' }}><CardContent sx={{ p: 3 }}><Typography variant="h6" fontWeight={700}>Fleet utilization</Typography><Typography color="text.secondary" variant="body2">Active rentals compared with the whole fleet</Typography><Typography variant="h2" fontWeight={800} mt={3}>{utilization}%</Typography><LinearProgress variant="determinate" value={utilization} sx={{ mt: 2, height: 12, borderRadius: 6, bgcolor: '#eee', '& .MuiLinearProgress-bar': { bgcolor: 'secondary.main' } }} /><Typography mt={2} color="text.secondary">{activeRentals} active rentals across {assets.length} assets</Typography></CardContent></Card></Grid><Grid size={{ xs: 12, md: 6 }}><Card variant="outlined" sx={{ height: '100%' }}><CardContent sx={{ p: 3 }}><Typography variant="h6" fontWeight={700}>Projected booking value</Typography><Typography color="text.secondary" variant="body2">Confirmed, active and completed booking days</Typography><Typography variant="h2" fontWeight={800} mt={3}>${projectedRevenue.toLocaleString('en-FJ', { minimumFractionDigits: 2 })}</Typography><Typography color="text.secondary">FJD before taxes, fees and adjustments</Typography></CardContent></Card></Grid></Grid>
    <Card variant="outlined" sx={{ mt: 2.5 }}><CardContent sx={{ p: 3 }}><Typography variant="h6" fontWeight={700} mb={2}>Fleet by branch</Typography><Stack spacing={2}>{branchCounts.map(([branch, count]) => <Box key={branch}><Stack direction="row" justifyContent="space-between" mb={.75}><Typography>{branch}</Typography><Typography fontWeight={700}>{count}</Typography></Stack><LinearProgress variant="determinate" value={assets.length ? count / assets.length * 100 : 0} sx={{ height: 8, borderRadius: 4 }} /></Box>)}</Stack></CardContent></Card>
    {profitability&&<Card variant="outlined" sx={{mt:2.5}}><CardContent sx={{p:3}}><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2} mb={2}><Box><Typography variant="h6" fontWeight={700}>Asset profit and loss</Typography><Typography variant="body2" color="text.secondary">Rental and service revenue less maintenance, personnel, transport and operating costs.</Typography></Box><Button variant="outlined" onClick={()=>void exportProfitability()}>Export CSV</Button></Stack><Grid container spacing={2} mb={2}>{[['Revenue',profitability.totals.revenue],['Expenses',profitability.totals.expense],['Gross profit',profitability.totals.profit]].map(([label,value])=><Grid key={String(label)} size={{xs:12,sm:4}}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="h5" fontWeight={800}>FJD {Number(value).toLocaleString('en-FJ',{minimumFractionDigits:2})}</Typography></Grid>)}</Grid><Box sx={{overflowX:'auto'}}><Table size="small"><TableHead><TableRow><TableCell>Asset</TableCell><TableCell align="right">Revenue</TableCell><TableCell align="right">Expense</TableCell><TableCell align="right">Profit</TableCell><TableCell align="right">Margin</TableCell><TableCell>Status</TableCell></TableRow></TableHead><TableBody>{profitability.assets.map(row=><TableRow key={row.id}><TableCell><Typography fontWeight={700}>{row.assetNumber}</Typography><Typography variant="caption" color="text.secondary">{row.name}</Typography></TableCell><TableCell align="right">${row.revenue.toLocaleString('en-FJ')}</TableCell><TableCell align="right">${row.totalExpense.toLocaleString('en-FJ')}</TableCell><TableCell align="right" sx={{color:row.lossMaking?'error.main':'success.main',fontWeight:800}}>${row.grossProfit.toLocaleString('en-FJ')}</TableCell><TableCell align="right">{row.profitMargin}%</TableCell><TableCell><Chip size="small" color={row.lossMaking?'error':'success'} label={row.lossMaking?'Needs attention':'Profitable'} /></TableCell></TableRow>)}</TableBody></Table></Box></CardContent></Card>}
    <Card variant="outlined" sx={{ mt: 2.5 }}><CardContent sx={{ p: 3 }}><Stack direction="row" justifyContent="space-between" mb={2}><Box><Typography variant="h6" fontWeight={700}>Recent audit activity</Typography><Typography variant="body2" color="text.secondary">Branch-secured history of operational changes</Typography></Box><Chip label={`${audit.length} events`} variant="outlined" /></Stack><Stack divider={<Divider flexItem />} spacing={0}>{audit.map((item) => <Stack key={item.id} direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" gap={1.5} py={1.5}><Box><Typography fontWeight={650}>{item.action}</Typography><Typography variant="body2" color="text.secondary">{item.summary}</Typography></Box><Box textAlign={{ sm: 'right' }}><Typography variant="body2">{item.userName}</Typography><Typography variant="caption" color="text.secondary">{new Date(item.occurredAt).toLocaleString('en-FJ')} {item.branchName ? `· ${item.branchName}` : ''}</Typography></Box></Stack>)}{audit.length === 0 && <Typography color="text.secondary" py={3}>No recorded changes yet. New workflow actions will appear here.</Typography>}</Stack></CardContent></Card></Box>
}
